# Site strings for all 20 languages. Theme names match the game's ARB files.
# Translated without native review (2026-10-01); English and Turkish are the
# reference copies.

LANGS = {
    'en': {'name': 'English', 'hreflang': 'en', 'og': 'en_US', 'path': ''},
    'tr': {'name': 'Türkçe', 'hreflang': 'tr', 'og': 'tr_TR', 'path': 'tr'},
    'de': {'name': 'Deutsch', 'hreflang': 'de', 'og': 'de_DE', 'path': 'de'},
    'es': {'name': 'Español', 'hreflang': 'es', 'og': 'es_ES', 'path': 'es'},
    'fr': {'name': 'Français', 'hreflang': 'fr', 'og': 'fr_FR', 'path': 'fr'},
    'it': {'name': 'Italiano', 'hreflang': 'it', 'og': 'it_IT', 'path': 'it'},
    'pt': {'name': 'Português', 'hreflang': 'pt', 'og': 'pt_BR', 'path': 'pt'},
    'nl': {'name': 'Nederlands', 'hreflang': 'nl', 'og': 'nl_NL', 'path': 'nl'},
    'pl': {'name': 'Polski', 'hreflang': 'pl', 'og': 'pl_PL', 'path': 'pl'},
    'sv': {'name': 'Svenska', 'hreflang': 'sv', 'og': 'sv_SE', 'path': 'sv'},
    'ru': {'name': 'Русский', 'hreflang': 'ru', 'og': 'ru_RU', 'path': 'ru'},
    'id': {'name': 'Bahasa Indonesia', 'hreflang': 'id', 'og': 'id_ID', 'path': 'id'},
    'vi': {'name': 'Tiếng Việt', 'hreflang': 'vi', 'og': 'vi_VN', 'path': 'vi'},
    'th': {'name': 'ไทย', 'hreflang': 'th', 'og': 'th_TH', 'path': 'th'},
    'hi': {'name': 'हिन्दी', 'hreflang': 'hi', 'og': 'hi_IN', 'path': 'hi'},
    'ar': {'name': 'العربية', 'hreflang': 'ar', 'og': 'ar_AR', 'path': 'ar', 'rtl': True},
    'ja': {'name': '日本語', 'hreflang': 'ja', 'og': 'ja_JP', 'path': 'ja'},
    'ko': {'name': '한국어', 'hreflang': 'ko', 'og': 'ko_KR', 'path': 'ko'},
    'zh': {'name': '简体中文', 'hreflang': 'zh-Hans', 'og': 'zh_CN', 'path': 'zh-hans'},
    'zh_Hant': {'name': '繁體中文', 'hreflang': 'zh-Hant', 'og': 'zh_TW', 'path': 'zh-hant'},
}

T = {}

T['en'] = dict(
    title='Ribbon Rush – A Cozy Block Puzzle for iPhone & Android',
    desc='Ribbon Rush is a free, cozy block puzzle. Drop satin ribbons on an 8×8 board, fill the ring around each gift and watch it wrap with a bow. Collect charms and unlock 16 themed worlds.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, gift wrap puzzle, cozy block puzzle, block puzzle game, relaxing puzzle game, christmas puzzle game, ribbon puzzle, casual game iPhone, Android puzzle game',
    skip='Skip to content', nav_label='Main', nav=['How to play', 'Demo', 'Themes', 'FAQ'], lang='Language',
    kicker='A cozy block puzzle',
    h1='Wrap every gift <em>with a bow</em>',
    sub='Drop satin ribbons on the board. When the ring around a gift is full, the ribbon ties itself, the bow pops, the lid flies off and stars rain down.',
    cta='Play the demo', soon='Coming soon', tap='Tap to wrap',
    how_h='How to play', how_p='Three moves, and you already know the whole game.',
    steps=[('Drop a ribbon', 'Pick one of three ribbon pieces and drop it anywhere it fits on the 8×8 board.'),
           ('Fill the ring', 'Every gift has a dashed ring around it. Cover each square of the ring with ribbon.'),
           ('Watch it wrap', 'The ribbon ties, the bow pops and the gift opens with confetti and stars. Full rows and columns clear too.')],
    demo_kicker='Right here, right now', demo_h='Try it in your browser',
    demo_p='A small version of the game. Your first gift is one ribbon away. Drag a piece from the tray onto the board.',
    demo=dict(score='Score', hintTut='One ribbon left for the first gift. Drop the <b>pink square</b> on the glowing spot.',
              hint='Place ribbons on the <b>dashed ring</b> around a gift. A full ring wraps the gift.',
              wrapped='Wrapped', chain='Chain', gold='Golden gift ×2', over='No room left', wrappedN='{n} gifts wrapped', again='Play again'),
    themes_h='Sixteen worlds to unlock',
    themes_p='Every theme is a whole scene, with its own board, ribbons, wrapping paper and wrap burst. Northern lights, a candy shop, a trip around the world, a spooky Halloween night and many more.',
    shot_alt='Ribbon Rush board in the {theme} theme',
    themes=dict(velvet='Velvet', winter='Winter', sweets='Candy Shop', travel='Voyage', halloween='Halloween Night'),
    charms_h='Collect little charms',
    charms_p='Wrapped gifts sometimes leave a charm behind. Find all 12 charms of an album and its theme is yours. Golden gifts hide the rare ones.',
    feat_h='Made for slow, happy minutes',
    feats=[('Free to play', 'Download and play for free. Star packs and ad removal are optional.'),
           ('No timers', 'Take your time. A game ends only when no piece fits.'),
           ('Plays offline', 'Your progress stays on your phone. No account needed.'),
           ('20 languages', 'From English and Türkçe to 日本語 and العربية.')],
    faq_h='Questions',
    faq=[('What is Ribbon Rush?', 'Ribbon Rush is a free, cozy block puzzle game for iPhone and Android by the independent studio Frame Labs. You place satin ribbon pieces on an 8×8 board to wrap gift boxes, earn stars, collect charms and unlock themed worlds.'),
         ('How do you play?', 'Drag ribbon pieces onto the board. Fill every square of the dashed ring around a gift to wrap it. Full rows and columns also clear. The game ends when none of your three pieces fits.'),
         ('Is it free?', 'Yes. The game is free with ads. You can buy stars or remove the ads between games, but you never have to.'),
         ('When does it come out?', 'Ribbon Rush is coming soon to the App Store and Google Play.'),
         ('What are charms and themes?', 'Charms are small collectibles that drop from wrapped gifts. Each album has 12. Finishing an album unlocks its theme, a new world for your board.'),
         ('Do I need the internet?', 'No, you can play offline. Ads and purchases need a connection.')],
    final_h='Your next gift is waiting',
    final_p='Ribbon Rush is coming soon to iPhone and Android.',
    made='Made with care', privacy='Privacy', support='Support',
)

T['tr'] = dict(
    title='Ribbon Rush – iPhone ve Android için huzurlu blok bulmaca',
    desc='Ribbon Rush ücretsiz, huzurlu bir blok bulmaca oyunu. 8×8 tahtaya saten kurdeleler yerleştir, her hediyenin çevresini doldur ve kutunun fiyonkla paketlenişini izle. Tılsım topla, 16 temalı dünyanın kilidini aç.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, hediye paketleme oyunu, blok bulmaca, rahatlatıcı bulmaca oyunu, yılbaşı oyunu, kurdele bulmaca, iPhone oyun, Android bulmaca oyunu',
    skip='İçeriğe geç', nav_label='Ana menü', nav=['Nasıl oynanır', 'Demo', 'Temalar', 'SSS'], lang='Dil',
    kicker='Huzurlu bir blok bulmaca',
    h1='Her hediyeyi <em>fiyonkla</em> paketle',
    sub='Tahtaya saten kurdeleler bırak. Bir hediyenin çevresi dolunca kurdele kendini bağlar, fiyonk açılır, kapak uçar ve yıldızlar yağar.',
    cta='Demoyu oyna', soon='Çok yakında', tap='Paketlemek için dokun',
    how_h='Nasıl oynanır', how_p='Üç hamle; oyunun tamamını öğrenmiş olursun.',
    steps=[('Kurdeleyi bırak', 'Üç kurdele parçasından birini seç ve 8×8 tahtada sığdığı herhangi bir yere bırak.'),
           ('Çevreyi doldur', 'Her hediyenin etrafında kesikli bir çember var. Çemberin her karesini kurdeleyle kapla.'),
           ('Paketlenişini izle', 'Kurdele bağlanır, fiyonk açılır, hediye konfeti ve yıldızlarla açılır. Dolu satır ve sütunlar da temizlenir.')],
    demo_kicker='Hemen burada', demo_h='Tarayıcında dene',
    demo_p='Oyunun küçük bir sürümü. İlk hediyene tek kurdele kaldı. Alttaki parçalardan birini tahtaya sürükle.',
    demo=dict(score='Puan', hintTut='İlk hediyeye tek kurdele kaldı. <b>Pembe kareyi</b> parlayan boşluğa bırak.',
              hint='Kurdeleleri hediyenin çevresindeki <b>kesikli çembere</b> diz. Çember dolunca hediye paketlenir.',
              wrapped='Paketlendi', chain='Zincir', gold='Altın hediye ×2', over='Yer kalmadı', wrappedN='{n} hediye paketlendi', again='Tekrar oyna'),
    themes_h='Açılacak on altı dünya',
    themes_p='Her tema bir sahne: kendi tahtası, kurdeleleri, paket kâğıtları ve paketleme patlaması var. Kuzey ışıkları, bir şekerci dükkânı, dünya turu, ürkütücü bir Cadılar Bayramı gecesi ve dahası.',
    shot_alt='{theme} temasında Ribbon Rush tahtası',
    themes=dict(velvet='Kadife', winter='Kış', sweets='Şekerci', travel='Seyahat', halloween='Cadı Gecesi'),
    charms_h='Minik tılsımlar topla',
    charms_p='Paketlenen hediyeler bazen arkalarında bir tılsım bırakır. Bir albümün 12 tılsımını bul, teması senin olsun. Nadir olanlar altın hediyelerde saklı.',
    feat_h='Yavaş ve mutlu dakikalar için',
    feats=[('Ücretsiz', 'İndir ve ücretsiz oyna. Yıldız paketleri ve reklam kaldırma isteğe bağlı.'),
           ('Süre yok', 'Acele etme. Oyun ancak hiçbir parça sığmadığında biter.'),
           ('İnternetsiz oynanır', 'İlerlemen telefonunda kalır. Hesap gerekmez.'),
           ('20 dil', 'English ve Türkçeden 日本語 ve العربيةya kadar.')],
    faq_h='Sorular',
    faq=[('Ribbon Rush nedir?', 'Ribbon Rush, bağımsız stüdyo Frame Labs tarafından iPhone ve Android için yapılan ücretsiz, huzurlu bir blok bulmaca oyunudur. 8×8 tahtaya saten kurdele parçaları yerleştirerek hediye kutularını paketler, yıldız kazanır, tılsım toplar ve temalı dünyaların kilidini açarsın.'),
         ('Nasıl oynanır?', 'Kurdele parçalarını tahtaya sürükle. Bir hediyeyi paketlemek için çevresindeki kesikli çemberin her karesini doldur. Dolu satır ve sütunlar da temizlenir. Üç parçandan hiçbiri sığmadığında oyun biter.'),
         ('Ücretsiz mi?', 'Evet. Oyun reklamlı ve ücretsizdir. İstersen yıldız satın alabilir ya da oyunlar arasındaki reklamları kaldırabilirsin; zorunlu değil.'),
         ('Ne zaman çıkıyor?', 'Ribbon Rush çok yakında App Store ve Google Play\'de.'),
         ('Tılsımlar ve temalar nedir?', 'Tılsımlar, paketlenen hediyelerden düşen küçük koleksiyon parçalarıdır. Her albümde 12 tane var. Bir albümü bitirince teması, yani tahtan için yeni bir dünya açılır.'),
         ('İnternet gerekiyor mu?', 'Hayır, internetsiz oynayabilirsin. Reklamlar ve satın almalar için bağlantı gerekir.')],
    final_h='Sıradaki hediyen seni bekliyor',
    final_p='Ribbon Rush çok yakında iPhone ve Android\'de.',
    made='Özenle yapıldı', privacy='Gizlilik', support='Destek',
)

T['de'] = dict(
    title='Ribbon Rush – Gemütliches Block-Puzzle für iPhone & Android',
    desc='Ribbon Rush ist ein kostenloses, gemütliches Block-Puzzle. Lege Satinbänder auf ein 8×8-Feld, fülle den Ring um jedes Geschenk und sieh zu, wie es mit einer Schleife verpackt wird. Sammle Anhänger und schalte 16 Themenwelten frei.',
    keywords='Ribbon Rush, Geschenke verpacken Spiel, Block Puzzle, entspannendes Puzzlespiel, Weihnachtsspiel, Puzzle iPhone, Puzzle Android',
    skip='Zum Inhalt', nav_label='Hauptmenü', nav=['Spielanleitung', 'Demo', 'Themen', 'FAQ'], lang='Sprache',
    kicker='Ein gemütliches Block-Puzzle',
    h1='Verpacke jedes Geschenk <em>mit Schleife</em>',
    sub='Lege Satinbänder auf das Feld. Ist der Ring um ein Geschenk voll, bindet sich das Band, die Schleife springt auf, der Deckel fliegt und Sterne regnen herab.',
    cta='Demo spielen', soon='Bald verfügbar', tap='Tippen zum Verpacken',
    how_h='So wird gespielt', how_p='Drei Züge, und du kennst das ganze Spiel.',
    steps=[('Band ablegen', 'Wähle eines von drei Bandteilen und lege es irgendwo auf das 8×8-Feld, wo es passt.'),
           ('Ring füllen', 'Jedes Geschenk hat einen gestrichelten Ring. Bedecke jedes Feld des Rings mit Band.'),
           ('Verpacken sehen', 'Das Band bindet sich, die Schleife springt auf und das Geschenk öffnet sich mit Konfetti und Sternen. Volle Reihen und Spalten verschwinden auch.')],
    demo_kicker='Gleich hier', demo_h='Im Browser ausprobieren',
    demo_p='Eine kleine Version des Spiels. Dein erstes Geschenk ist nur ein Band entfernt. Ziehe ein Teil auf das Feld.',
    demo=dict(score='Punkte', hintTut='Noch ein Band bis zum ersten Geschenk. Lege das <b>rosa Quadrat</b> auf das leuchtende Feld.',
              hint='Lege Bänder auf den <b>gestrichelten Ring</b> um ein Geschenk. Ein voller Ring verpackt es.',
              wrapped='Verpackt', chain='Kette', gold='Goldenes Geschenk ×2', over='Kein Platz mehr', wrappedN='{n} Geschenke verpackt', again='Nochmal spielen'),
    themes_h='Sechzehn Welten zum Freischalten',
    themes_p='Jedes Thema ist eine ganze Szene mit eigenem Feld, eigenen Bändern, Geschenkpapieren und Effekten. Polarlichter, ein Süßwarenladen, eine Weltreise, eine schaurige Halloween-Nacht und mehr.',
    shot_alt='Ribbon Rush im Thema {theme}',
    themes=dict(velvet='Samt', winter='Winter', sweets='Süßwarenladen', travel='Reise', halloween='Halloween-Nacht'),
    charms_h='Sammle kleine Anhänger',
    charms_p='Verpackte Geschenke hinterlassen manchmal einen Anhänger. Finde alle 12 eines Albums und sein Thema gehört dir. Goldene Geschenke verstecken die seltenen.',
    feat_h='Für ruhige, glückliche Minuten',
    feats=[('Kostenlos', 'Kostenlos laden und spielen. Sternpakete und Werbefreiheit sind optional.'),
           ('Kein Zeitdruck', 'Lass dir Zeit. Ein Spiel endet erst, wenn kein Teil mehr passt.'),
           ('Offline spielbar', 'Dein Fortschritt bleibt auf deinem Handy. Kein Konto nötig.'),
           ('20 Sprachen', 'Von English und Deutsch bis 日本語 und العربية.')],
    faq_h='Fragen',
    faq=[('Was ist Ribbon Rush?', 'Ribbon Rush ist ein kostenloses, gemütliches Block-Puzzle für iPhone und Android vom unabhängigen Studio Frame Labs. Du legst Satinbänder auf ein 8×8-Feld, verpackst Geschenke, sammelst Sterne und Anhänger und schaltest Themenwelten frei.'),
         ('Wie spielt man?', 'Ziehe Bandteile auf das Feld. Fülle jedes Feld des gestrichelten Rings um ein Geschenk, um es zu verpacken. Volle Reihen und Spalten verschwinden. Das Spiel endet, wenn keines deiner drei Teile mehr passt.'),
         ('Ist es kostenlos?', 'Ja. Das Spiel ist kostenlos mit Werbung. Du kannst Sterne kaufen oder die Werbung zwischen den Spielen entfernen, musst aber nicht.'),
         ('Wann erscheint es?', 'Ribbon Rush erscheint bald im App Store und bei Google Play.'),
         ('Was sind Anhänger und Themen?', 'Anhänger sind kleine Sammelstücke aus verpackten Geschenken. Jedes Album hat 12. Ein volles Album schaltet sein Thema frei, eine neue Welt für dein Feld.'),
         ('Brauche ich Internet?', 'Nein, du kannst offline spielen. Werbung und Käufe brauchen eine Verbindung.')],
    final_h='Dein nächstes Geschenk wartet',
    final_p='Ribbon Rush kommt bald für iPhone und Android.',
    made='Mit Liebe gemacht', privacy='Datenschutz', support='Support',
)

T['es'] = dict(
    title='Ribbon Rush – Un puzle de bloques acogedor para iPhone y Android',
    desc='Ribbon Rush es un puzle de bloques gratis y acogedor. Coloca cintas de satén en un tablero de 8×8, llena el anillo de cada regalo y míralo envolverse con un lazo. Colecciona amuletos y desbloquea 16 mundos temáticos.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, juego de envolver regalos, puzle de bloques, juego de puzle relajante, juego de navidad, puzle iPhone, puzle Android',
    skip='Ir al contenido', nav_label='Principal', nav=['Cómo se juega', 'Demo', 'Temas', 'Preguntas'], lang='Idioma',
    kicker='Un puzle de bloques acogedor',
    h1='Envuelve cada regalo <em>con un lazo</em>',
    sub='Coloca cintas de satén en el tablero. Cuando el anillo de un regalo se llena, la cinta se ata, el lazo aparece, la tapa sale volando y llueven estrellas.',
    cta='Jugar la demo', soon='Muy pronto', tap='Toca para envolver',
    how_h='Cómo se juega', how_p='Tres movimientos y ya conoces todo el juego.',
    steps=[('Coloca una cinta', 'Elige una de las tres piezas de cinta y colócala donde quepa en el tablero de 8×8.'),
           ('Llena el anillo', 'Cada regalo tiene un anillo punteado. Cubre cada casilla del anillo con cinta.'),
           ('Míralo envolverse', 'La cinta se ata, el lazo aparece y el regalo se abre con confeti y estrellas. Las filas y columnas llenas también se borran.')],
    demo_kicker='Aquí mismo', demo_h='Pruébalo en tu navegador',
    demo_p='Una versión pequeña del juego. Tu primer regalo está a una cinta. Arrastra una pieza al tablero.',
    demo=dict(score='Puntos', hintTut='Falta una cinta para el primer regalo. Suelta el <b>cuadrado rosa</b> en la casilla que brilla.',
              hint='Coloca cintas en el <b>anillo punteado</b> de un regalo. Un anillo lleno lo envuelve.',
              wrapped='Envuelto', chain='Cadena', gold='Regalo dorado ×2', over='No queda espacio', wrappedN='{n} regalos envueltos', again='Jugar otra vez'),
    themes_h='Dieciséis mundos por desbloquear',
    themes_p='Cada tema es una escena completa, con su tablero, cintas, papeles y explosión propios. Auroras boreales, una dulcería, un viaje por el mundo, una noche de Halloween y mucho más.',
    shot_alt='Tablero de Ribbon Rush con el tema {theme}',
    themes=dict(velvet='Terciopelo', winter='Invierno', sweets='Dulcería', travel='Viaje', halloween='Noche de Halloween'),
    charms_h='Colecciona amuletos',
    charms_p='Los regalos envueltos a veces dejan un amuleto. Encuentra los 12 de un álbum y su tema será tuyo. Los regalos dorados esconden los raros.',
    feat_h='Para minutos tranquilos y felices',
    feats=[('Gratis', 'Descárgalo y juega gratis. Los paquetes de estrellas y quitar anuncios son opcionales.'),
           ('Sin relojes', 'Tómate tu tiempo. La partida solo termina cuando ninguna pieza cabe.'),
           ('Sin conexión', 'Tu progreso se queda en tu teléfono. No necesitas cuenta.'),
           ('20 idiomas', 'Del English y el Español al 日本語 y العربية.')],
    faq_h='Preguntas',
    faq=[('¿Qué es Ribbon Rush?', 'Ribbon Rush es un puzle de bloques gratis y acogedor para iPhone y Android del estudio independiente Frame Labs. Colocas piezas de cinta en un tablero de 8×8 para envolver regalos, ganar estrellas, coleccionar amuletos y desbloquear mundos temáticos.'),
         ('¿Cómo se juega?', 'Arrastra piezas de cinta al tablero. Llena cada casilla del anillo punteado de un regalo para envolverlo. Las filas y columnas llenas se borran. La partida termina cuando ninguna de tus tres piezas cabe.'),
         ('¿Es gratis?', 'Sí. El juego es gratis con anuncios. Puedes comprar estrellas o quitar los anuncios entre partidas, pero no es obligatorio.'),
         ('¿Cuándo sale?', 'Ribbon Rush llegará muy pronto a la App Store y Google Play.'),
         ('¿Qué son los amuletos y los temas?', 'Los amuletos son pequeños coleccionables que caen de los regalos envueltos. Cada álbum tiene 12. Completar un álbum desbloquea su tema, un mundo nuevo para tu tablero.'),
         ('¿Necesito internet?', 'No, puedes jugar sin conexión. Los anuncios y las compras necesitan conexión.')],
    final_h='Tu próximo regalo te espera',
    final_p='Ribbon Rush llega muy pronto a iPhone y Android.',
    made='Hecho con cariño', privacy='Privacidad', support='Soporte',
)

T['fr'] = dict(
    title='Ribbon Rush – Un puzzle de blocs douillet pour iPhone et Android',
    desc='Ribbon Rush est un puzzle de blocs gratuit et douillet. Pose des rubans de satin sur un plateau 8×8, remplis le cercle autour de chaque cadeau et regarde-le s\'emballer avec un nœud. Collectionne des breloques et débloque 16 univers.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, jeu emballage cadeau, puzzle de blocs, jeu de puzzle relaxant, jeu de noël, puzzle iPhone, puzzle Android',
    skip='Aller au contenu', nav_label='Principal', nav=['Comment jouer', 'Démo', 'Thèmes', 'FAQ'], lang='Langue',
    kicker='Un puzzle de blocs douillet',
    h1='Emballe chaque cadeau <em>avec un nœud</em>',
    sub='Pose des rubans de satin sur le plateau. Quand le cercle d\'un cadeau est plein, le ruban se noue, le nœud éclot, le couvercle s\'envole et les étoiles pleuvent.',
    cta='Jouer à la démo', soon='Bientôt disponible', tap='Touche pour emballer',
    how_h='Comment jouer', how_p='Trois coups, et tu connais tout le jeu.',
    steps=[('Pose un ruban', 'Choisis une des trois pièces de ruban et pose-la où elle tient sur le plateau 8×8.'),
           ('Remplis le cercle', 'Chaque cadeau a un cercle en pointillés. Couvre chaque case du cercle avec du ruban.'),
           ('Regarde-le s\'emballer', 'Le ruban se noue, le nœud éclot et le cadeau s\'ouvre en confettis et étoiles. Les lignes et colonnes pleines s\'effacent aussi.')],
    demo_kicker='Ici même', demo_h='Essaie dans ton navigateur',
    demo_p='Une petite version du jeu. Ton premier cadeau n\'est qu\'à un ruban. Fais glisser une pièce sur le plateau.',
    demo=dict(score='Score', hintTut='Plus qu\'un ruban pour le premier cadeau. Pose le <b>carré rose</b> sur la case qui brille.',
              hint='Pose des rubans sur le <b>cercle en pointillés</b> d\'un cadeau. Un cercle plein l\'emballe.',
              wrapped='Emballé', chain='Chaîne', gold='Cadeau doré ×2', over='Plus de place', wrappedN='{n} cadeaux emballés', again='Rejouer'),
    themes_h='Seize univers à débloquer',
    themes_p='Chaque thème est une scène entière, avec son plateau, ses rubans, ses papiers et son explosion. Aurores boréales, confiserie, tour du monde, nuit d\'Halloween et bien plus.',
    shot_alt='Plateau de Ribbon Rush avec le thème {theme}',
    themes=dict(velvet='Velours', winter='Hiver', sweets='Confiserie', travel='Voyage', halloween="Nuit d'Halloween"),
    charms_h='Collectionne des breloques',
    charms_p='Les cadeaux emballés laissent parfois une breloque. Trouve les 12 d\'un album et son thème est à toi. Les cadeaux dorés cachent les plus rares.',
    feat_h='Pour des minutes douces et heureuses',
    feats=[('Gratuit', 'Télécharge et joue gratuitement. Packs d\'étoiles et suppression des pubs en option.'),
           ('Sans chrono', 'Prends ton temps. La partie ne finit que quand plus aucune pièce ne tient.'),
           ('Hors ligne', 'Ta progression reste sur ton téléphone. Aucun compte requis.'),
           ('20 langues', 'De l\'English et du Français au 日本語 et à l\'العربية.')],
    faq_h='Questions',
    faq=[('Qu\'est-ce que Ribbon Rush ?', 'Ribbon Rush est un puzzle de blocs gratuit et douillet pour iPhone et Android, créé par le studio indépendant Frame Labs. Tu poses des rubans sur un plateau 8×8 pour emballer des cadeaux, gagner des étoiles, collectionner des breloques et débloquer des univers.'),
         ('Comment joue-t-on ?', 'Fais glisser des pièces de ruban sur le plateau. Remplis chaque case du cercle en pointillés d\'un cadeau pour l\'emballer. Les lignes et colonnes pleines s\'effacent. La partie finit quand aucune de tes trois pièces ne tient.'),
         ('Est-ce gratuit ?', 'Oui. Le jeu est gratuit avec publicités. Tu peux acheter des étoiles ou retirer les pubs entre les parties, sans obligation.'),
         ('Quand sort-il ?', 'Ribbon Rush arrive bientôt sur l\'App Store et Google Play.'),
         ('Que sont les breloques et les thèmes ?', 'Les breloques sont de petits objets à collectionner qui tombent des cadeaux emballés. Chaque album en compte 12. Terminer un album débloque son thème, un nouvel univers pour ton plateau.'),
         ('Faut-il internet ?', 'Non, tu peux jouer hors ligne. Les pubs et les achats demandent une connexion.')],
    final_h='Ton prochain cadeau t\'attend',
    final_p='Ribbon Rush arrive bientôt sur iPhone et Android.',
    made='Fait avec soin', privacy='Confidentialité', support='Assistance',
)

T['it'] = dict(
    title='Ribbon Rush – Un puzzle a blocchi rilassante per iPhone e Android',
    desc='Ribbon Rush è un puzzle a blocchi gratuito e rilassante. Posa nastri di raso su una griglia 8×8, riempi l\'anello attorno a ogni regalo e guardalo incartarsi con un fiocco. Colleziona ciondoli e sblocca 16 mondi a tema.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, gioco incartare regali, puzzle a blocchi, gioco puzzle rilassante, gioco di natale, puzzle iPhone, puzzle Android',
    skip='Vai al contenuto', nav_label='Principale', nav=['Come si gioca', 'Demo', 'Temi', 'FAQ'], lang='Lingua',
    kicker='Un puzzle a blocchi rilassante',
    h1='Incarta ogni regalo <em>con un fiocco</em>',
    sub='Posa nastri di raso sulla griglia. Quando l\'anello di un regalo è pieno, il nastro si lega, il fiocco spunta, il coperchio vola via e piovono stelle.',
    cta='Gioca la demo', soon='In arrivo', tap='Tocca per incartare',
    how_h='Come si gioca', how_p='Tre mosse e conosci già tutto il gioco.',
    steps=[('Posa un nastro', 'Scegli uno dei tre pezzi di nastro e posalo dove c\'è spazio sulla griglia 8×8.'),
           ('Riempi l\'anello', 'Ogni regalo ha un anello tratteggiato. Copri ogni casella dell\'anello con il nastro.'),
           ('Guardalo incartarsi', 'Il nastro si lega, il fiocco spunta e il regalo si apre tra coriandoli e stelle. Anche righe e colonne piene spariscono.')],
    demo_kicker='Proprio qui', demo_h='Provalo nel browser',
    demo_p='Una piccola versione del gioco. Il tuo primo regalo è a un nastro di distanza. Trascina un pezzo sulla griglia.',
    demo=dict(score='Punti', hintTut='Manca un nastro al primo regalo. Posa il <b>quadrato rosa</b> sulla casella che brilla.',
              hint='Posa i nastri sull\'<b>anello tratteggiato</b> di un regalo. Un anello pieno lo incarta.',
              wrapped='Incartato', chain='Catena', gold='Regalo d\'oro ×2', over='Niente più spazio', wrappedN='{n} regali incartati', again='Gioca ancora'),
    themes_h='Sedici mondi da sbloccare',
    themes_p='Ogni tema è una scena intera, con griglia, nastri, carte da regalo ed esplosione propri. Aurore boreali, una pasticceria, un giro del mondo, una notte di Halloween e molto altro.',
    shot_alt='Griglia di Ribbon Rush con il tema {theme}',
    themes=dict(velvet='Velluto', winter='Inverno', sweets='Pasticceria', travel='Viaggio', halloween='Notte di Halloween'),
    charms_h='Colleziona piccoli ciondoli',
    charms_p='I regali incartati a volte lasciano un ciondolo. Trova tutti i 12 di un album e il suo tema è tuo. I regali d\'oro nascondono i più rari.',
    feat_h='Per minuti lenti e felici',
    feats=[('Gratis', 'Scarica e gioca gratis. Pacchetti di stelle e rimozione pubblicità facoltativi.'),
           ('Niente timer', 'Prenditi il tuo tempo. La partita finisce solo quando nessun pezzo entra.'),
           ('Offline', 'I tuoi progressi restano sul telefono. Nessun account.'),
           ('20 lingue', 'Dall\'English e l\'Italiano al 日本語 e all\'العربية.')],
    faq_h='Domande',
    faq=[('Cos\'è Ribbon Rush?', 'Ribbon Rush è un puzzle a blocchi gratuito e rilassante per iPhone e Android dello studio indipendente Frame Labs. Posi pezzi di nastro su una griglia 8×8 per incartare regali, guadagnare stelle, collezionare ciondoli e sbloccare mondi a tema.'),
         ('Come si gioca?', 'Trascina i pezzi di nastro sulla griglia. Riempi ogni casella dell\'anello tratteggiato di un regalo per incartarlo. Righe e colonne piene spariscono. La partita finisce quando nessuno dei tre pezzi entra.'),
         ('È gratis?', 'Sì. Il gioco è gratuito con pubblicità. Puoi comprare stelle o togliere la pubblicità tra le partite, ma non è obbligatorio.'),
         ('Quando esce?', 'Ribbon Rush arriva presto su App Store e Google Play.'),
         ('Cosa sono ciondoli e temi?', 'I ciondoli sono piccoli oggetti da collezione che cadono dai regali incartati. Ogni album ne ha 12. Completare un album sblocca il suo tema, un nuovo mondo per la tua griglia.'),
         ('Serve internet?', 'No, puoi giocare offline. Pubblicità e acquisti richiedono una connessione.')],
    final_h='Il tuo prossimo regalo ti aspetta',
    final_p='Ribbon Rush arriva presto su iPhone e Android.',
    made='Fatto con cura', privacy='Privacy', support='Assistenza',
)

T['pt'] = dict(
    title='Ribbon Rush – Um quebra-cabeça de blocos aconchegante para iPhone e Android',
    desc='Ribbon Rush é um quebra-cabeça de blocos grátis e aconchegante. Coloque fitas de cetim num tabuleiro 8×8, preencha o anel de cada presente e veja-o embrulhar-se com um laço. Colecione berloques e desbloqueie 16 mundos temáticos.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, jogo de embrulhar presentes, quebra-cabeça de blocos, jogo relaxante, jogo de natal, puzzle iPhone, puzzle Android',
    skip='Ir para o conteúdo', nav_label='Principal', nav=['Como jogar', 'Demo', 'Temas', 'Perguntas'], lang='Idioma',
    kicker='Um quebra-cabeça de blocos aconchegante',
    h1='Embrulhe cada presente <em>com um laço</em>',
    sub='Coloque fitas de cetim no tabuleiro. Quando o anel de um presente fica cheio, a fita se amarra, o laço aparece, a tampa voa e chovem estrelas.',
    cta='Jogar a demo', soon='Em breve', tap='Toque para embrulhar',
    how_h='Como jogar', how_p='Três jogadas e você já conhece o jogo todo.',
    steps=[('Coloque uma fita', 'Escolha uma das três peças de fita e coloque-a onde couber no tabuleiro 8×8.'),
           ('Preencha o anel', 'Cada presente tem um anel tracejado. Cubra cada casa do anel com fita.'),
           ('Veja embrulhar', 'A fita se amarra, o laço aparece e o presente se abre com confete e estrelas. Linhas e colunas cheias também somem.')],
    demo_kicker='Aqui mesmo', demo_h='Experimente no navegador',
    demo_p='Uma versão pequena do jogo. Seu primeiro presente está a uma fita. Arraste uma peça para o tabuleiro.',
    demo=dict(score='Pontos', hintTut='Falta uma fita para o primeiro presente. Solte o <b>quadrado rosa</b> na casa que brilha.',
              hint='Coloque fitas no <b>anel tracejado</b> de um presente. Um anel cheio o embrulha.',
              wrapped='Embrulhado', chain='Corrente', gold='Presente dourado ×2', over='Sem espaço', wrappedN='{n} presentes embrulhados', again='Jogar de novo'),
    themes_h='Dezesseis mundos para desbloquear',
    themes_p='Cada tema é uma cena inteira, com tabuleiro, fitas, papéis e explosão próprios. Auroras boreais, uma doceria, uma volta ao mundo, uma noite de Halloween e muito mais.',
    shot_alt='Tabuleiro do Ribbon Rush com o tema {theme}',
    themes=dict(velvet='Veludo', winter='Inverno', sweets='Doceria', travel='Viagem', halloween='Noite de Halloween'),
    charms_h='Colecione berloques',
    charms_p='Presentes embrulhados às vezes deixam um berloque. Encontre os 12 de um álbum e o tema é seu. Os presentes dourados escondem os raros.',
    feat_h='Para minutos calmos e felizes',
    feats=[('Grátis', 'Baixe e jogue de graça. Pacotes de estrelas e remover anúncios são opcionais.'),
           ('Sem cronômetro', 'Vá no seu ritmo. A partida só acaba quando nenhuma peça cabe.'),
           ('Funciona offline', 'Seu progresso fica no seu celular. Sem conta.'),
           ('20 idiomas', 'Do English e Português ao 日本語 e العربية.')],
    faq_h='Perguntas',
    faq=[('O que é o Ribbon Rush?', 'Ribbon Rush é um quebra-cabeça de blocos grátis e aconchegante para iPhone e Android, do estúdio independente Frame Labs. Você coloca peças de fita num tabuleiro 8×8 para embrulhar presentes, ganhar estrelas, colecionar berloques e desbloquear mundos temáticos.'),
         ('Como se joga?', 'Arraste peças de fita para o tabuleiro. Preencha cada casa do anel tracejado de um presente para embrulhá-lo. Linhas e colunas cheias somem. A partida acaba quando nenhuma das três peças cabe.'),
         ('É grátis?', 'Sim. O jogo é grátis com anúncios. Você pode comprar estrelas ou remover os anúncios entre partidas, mas não precisa.'),
         ('Quando sai?', 'Ribbon Rush chega em breve à App Store e ao Google Play.'),
         ('O que são berloques e temas?', 'Berloques são pequenos colecionáveis que caem dos presentes embrulhados. Cada álbum tem 12. Completar um álbum desbloqueia o tema dele, um novo mundo para o seu tabuleiro.'),
         ('Preciso de internet?', 'Não, dá para jogar offline. Anúncios e compras precisam de conexão.')],
    final_h='Seu próximo presente está esperando',
    final_p='Ribbon Rush chega em breve ao iPhone e Android.',
    made='Feito com carinho', privacy='Privacidade', support='Suporte',
)

T['nl'] = dict(
    title='Ribbon Rush – Een gezellige blokpuzzel voor iPhone en Android',
    desc='Ribbon Rush is een gratis, gezellige blokpuzzel. Leg satijnen linten op een 8×8-bord, vul de ring rond elk cadeau en kijk hoe het met een strik wordt ingepakt. Verzamel bedels en ontgrendel 16 themawerelden.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, cadeau inpakken spel, blokpuzzel, ontspannend puzzelspel, kerstspel, puzzel iPhone, puzzel Android',
    skip='Naar inhoud', nav_label='Hoofdmenu', nav=['Zo speel je', 'Demo', "Thema's", 'Vragen'], lang='Taal',
    kicker='Een gezellige blokpuzzel',
    h1='Pak elk cadeau in <em>met een strik</em>',
    sub='Leg satijnen linten op het bord. Is de ring rond een cadeau vol, dan knoopt het lint zich, springt de strik open, vliegt het deksel eraf en regent het sterren.',
    cta='Speel de demo', soon='Binnenkort', tap='Tik om in te pakken',
    how_h='Zo speel je', how_p='Drie zetten en je kent het hele spel.',
    steps=[('Leg een lint', 'Kies een van drie lintstukken en leg het waar het past op het 8×8-bord.'),
           ('Vul de ring', 'Elk cadeau heeft een gestippelde ring. Bedek elk vakje van de ring met lint.'),
           ('Kijk hoe het inpakt', 'Het lint knoopt, de strik springt open en het cadeau gaat open met confetti en sterren. Volle rijen en kolommen verdwijnen ook.')],
    demo_kicker='Gewoon hier', demo_h='Probeer het in je browser',
    demo_p='Een kleine versie van het spel. Je eerste cadeau is één lint verwijderd. Sleep een stuk naar het bord.',
    demo=dict(score='Score', hintTut='Nog één lint voor het eerste cadeau. Leg het <b>roze vierkantje</b> op het oplichtende vakje.',
              hint='Leg linten op de <b>gestippelde ring</b> rond een cadeau. Een volle ring pakt het in.',
              wrapped='Ingepakt', chain='Ketting', gold='Gouden cadeau ×2', over='Geen plek meer', wrappedN='{n} cadeaus ingepakt', again='Opnieuw spelen'),
    themes_h='Zestien werelden om te ontgrendelen',
    themes_p='Elk thema is een hele scène, met eigen bord, linten, inpakpapier en effect. Noorderlicht, een snoepwinkel, een wereldreis, een griezelige Halloweennacht en meer.',
    shot_alt='Ribbon Rush-bord in het thema {theme}',
    themes=dict(velvet='Fluweel', winter='Winter', sweets='Snoepwinkel', travel='Reis', halloween='Halloweennacht'),
    charms_h='Verzamel kleine bedels',
    charms_p='Ingepakte cadeaus laten soms een bedel achter. Vind alle 12 van een album en het thema is van jou. Gouden cadeaus verbergen de zeldzame.',
    feat_h='Voor rustige, blije minuten',
    feats=[('Gratis', 'Download en speel gratis. Sterrenpakketten en advertenties uitzetten zijn optioneel.'),
           ('Geen timers', 'Neem je tijd. Een spel eindigt pas als geen stuk meer past.'),
           ('Speelt offline', 'Je voortgang blijft op je telefoon. Geen account nodig.'),
           ('20 talen', 'Van English en Nederlands tot 日本語 en العربية.')],
    faq_h='Vragen',
    faq=[('Wat is Ribbon Rush?', 'Ribbon Rush is een gratis, gezellige blokpuzzel voor iPhone en Android van de onafhankelijke studio Frame Labs. Je legt lintstukken op een 8×8-bord om cadeaus in te pakken, sterren te verdienen, bedels te verzamelen en themawerelden te ontgrendelen.'),
         ('Hoe speel je?', 'Sleep lintstukken naar het bord. Vul elk vakje van de gestippelde ring rond een cadeau om het in te pakken. Volle rijen en kolommen verdwijnen. Het spel eindigt als geen van je drie stukken past.'),
         ('Is het gratis?', 'Ja. Het spel is gratis met advertenties. Je kunt sterren kopen of de advertenties tussen spellen uitzetten, maar het hoeft niet.'),
         ('Wanneer komt het uit?', 'Ribbon Rush komt binnenkort naar de App Store en Google Play.'),
         ("Wat zijn bedels en thema's?", 'Bedels zijn kleine verzamelobjecten uit ingepakte cadeaus. Elk album heeft er 12. Een vol album ontgrendelt zijn thema, een nieuwe wereld voor je bord.'),
         ('Heb ik internet nodig?', 'Nee, je kunt offline spelen. Advertenties en aankopen hebben een verbinding nodig.')],
    final_h='Je volgende cadeau wacht',
    final_p='Ribbon Rush komt binnenkort naar iPhone en Android.',
    made='Met zorg gemaakt', privacy='Privacy', support='Support',
)

T['pl'] = dict(
    title='Ribbon Rush – Przytulna łamigłówka z klockami na iPhone i Androida',
    desc='Ribbon Rush to darmowa, przytulna łamigłówka z klockami. Układaj satynowe wstążki na planszy 8×8, wypełnij pierścień wokół prezentu i patrz, jak pakuje się z kokardą. Zbieraj zawieszki i odblokuj 16 tematycznych światów.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, gra pakowanie prezentów, łamigłówka z klockami, relaksująca gra logiczna, gra świąteczna, puzzle iPhone, puzzle Android',
    skip='Przejdź do treści', nav_label='Menu', nav=['Jak grać', 'Demo', 'Motywy', 'Pytania'], lang='Język',
    kicker='Przytulna łamigłówka z klockami',
    h1='Zapakuj każdy prezent <em>z kokardą</em>',
    sub='Układaj satynowe wstążki na planszy. Gdy pierścień wokół prezentu się zapełni, wstążka się zawiąże, kokarda wyskoczy, wieczko odleci, a z nieba posypią się gwiazdki.',
    cta='Zagraj w demo', soon='Już wkrótce', tap='Dotknij, by zapakować',
    how_h='Jak grać', how_p='Trzy ruchy i znasz całą grę.',
    steps=[('Połóż wstążkę', 'Wybierz jeden z trzech kawałków wstążki i połóż go tam, gdzie pasuje na planszy 8×8.'),
           ('Wypełnij pierścień', 'Każdy prezent ma przerywany pierścień. Zakryj wstążką każde jego pole.'),
           ('Patrz, jak się pakuje', 'Wstążka się zawiązuje, kokarda wyskakuje, a prezent otwiera się w konfetti i gwiazdkach. Pełne rzędy i kolumny też znikają.')],
    demo_kicker='Właśnie tutaj', demo_h='Wypróbuj w przeglądarce',
    demo_p='Mała wersja gry. Pierwszy prezent dzieli cię od jednej wstążki. Przeciągnij kawałek na planszę.',
    demo=dict(score='Wynik', hintTut='Jeszcze jedna wstążka do pierwszego prezentu. Upuść <b>różowy kwadrat</b> na świecące pole.',
              hint='Układaj wstążki na <b>przerywanym pierścieniu</b> wokół prezentu. Pełny pierścień go pakuje.',
              wrapped='Zapakowane', chain='Łańcuch', gold='Złoty prezent ×2', over='Brak miejsca', wrappedN='Zapakowane prezenty: {n}', again='Zagraj ponownie'),
    themes_h='Szesnaście światów do odblokowania',
    themes_p='Każdy motyw to cała scena z własną planszą, wstążkami, papierem i efektem. Zorza polarna, cukiernia, podróż dookoła świata, straszna noc Halloween i więcej.',
    shot_alt='Plansza Ribbon Rush w motywie {theme}',
    themes=dict(velvet='Aksamit', winter='Zima', sweets='Cukiernia', travel='Podróż', halloween='Noc Halloween'),
    charms_h='Zbieraj małe zawieszki',
    charms_p='Zapakowane prezenty czasem zostawiają zawieszkę. Znajdź wszystkie 12 z albumu, a jego motyw będzie twój. Złote prezenty kryją te rzadkie.',
    feat_h='Na spokojne, szczęśliwe chwile',
    feats=[('Za darmo', 'Pobierz i graj za darmo. Pakiety gwiazdek i usunięcie reklam są opcjonalne.'),
           ('Bez zegara', 'Nie spiesz się. Gra kończy się dopiero, gdy żaden kawałek nie pasuje.'),
           ('Działa offline', 'Postępy zostają w telefonie. Bez konta.'),
           ('20 języków', 'Od English i polskiego po 日本語 i العربية.')],
    faq_h='Pytania',
    faq=[('Czym jest Ribbon Rush?', 'Ribbon Rush to darmowa, przytulna łamigłówka z klockami na iPhone i Androida od niezależnego studia Frame Labs. Układasz kawałki wstążek na planszy 8×8, by pakować prezenty, zdobywać gwiazdki, zbierać zawieszki i odblokowywać tematyczne światy.'),
         ('Jak się gra?', 'Przeciągaj kawałki wstążek na planszę. Wypełnij każde pole przerywanego pierścienia wokół prezentu, by go zapakować. Pełne rzędy i kolumny znikają. Gra kończy się, gdy żaden z trzech kawałków nie pasuje.'),
         ('Czy jest darmowa?', 'Tak. Gra jest darmowa z reklamami. Możesz kupić gwiazdki lub usunąć reklamy między grami, ale nie musisz.'),
         ('Kiedy premiera?', 'Ribbon Rush już wkrótce w App Store i Google Play.'),
         ('Czym są zawieszki i motywy?', 'Zawieszki to małe przedmioty kolekcjonerskie wypadające z zapakowanych prezentów. Każdy album ma ich 12. Ukończenie albumu odblokowuje jego motyw, nowy świat dla twojej planszy.'),
         ('Czy potrzebuję internetu?', 'Nie, możesz grać offline. Reklamy i zakupy wymagają połączenia.')],
    final_h='Twój następny prezent czeka',
    final_p='Ribbon Rush już wkrótce na iPhone i Androida.',
    made='Zrobione z troską', privacy='Prywatność', support='Pomoc',
)

T['sv'] = dict(
    title='Ribbon Rush – Ett mysigt blockpussel för iPhone och Android',
    desc='Ribbon Rush är ett gratis, mysigt blockpussel. Lägg satinband på en 8×8-bräda, fyll ringen runt varje paket och se det slås in med en rosett. Samla berlocker och lås upp 16 temavärldar.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, slå in paket spel, blockpussel, avkopplande pusselspel, julspel, pussel iPhone, pussel Android',
    skip='Till innehållet', nav_label='Huvudmeny', nav=['Så spelar du', 'Demo', 'Teman', 'Frågor'], lang='Språk',
    kicker='Ett mysigt blockpussel',
    h1='Slå in varje paket <em>med rosett</em>',
    sub='Lägg satinband på brädan. När ringen runt ett paket är full knyts bandet, rosetten slår ut, locket flyger och det regnar stjärnor.',
    cta='Spela demon', soon='Kommer snart', tap='Tryck för att slå in',
    how_h='Så spelar du', how_p='Tre drag, och du kan hela spelet.',
    steps=[('Lägg ett band', 'Välj en av tre bandbitar och lägg den där den får plats på 8×8-brädan.'),
           ('Fyll ringen', 'Varje paket har en streckad ring. Täck varje ruta i ringen med band.'),
           ('Se det slås in', 'Bandet knyts, rosetten slår ut och paketet öppnas med konfetti och stjärnor. Fulla rader och kolumner försvinner också.')],
    demo_kicker='Precis här', demo_h='Testa i webbläsaren',
    demo_p='En liten version av spelet. Ditt första paket är ett band bort. Dra en bit till brädan.',
    demo=dict(score='Poäng', hintTut='Ett band kvar till första paketet. Släpp den <b>rosa rutan</b> på den lysande platsen.',
              hint='Lägg band på den <b>streckade ringen</b> runt ett paket. En full ring slår in det.',
              wrapped='Inslaget', chain='Kedja', gold='Gyllene paket ×2', over='Ingen plats kvar', wrappedN='{n} paket inslagna', again='Spela igen'),
    themes_h='Sexton världar att låsa upp',
    themes_p='Varje tema är en hel scen med egen bräda, egna band, papper och effekter. Norrsken, en godisbutik, en resa runt jorden, en kuslig halloweennatt och mer.',
    shot_alt='Ribbon Rush-brädan i temat {theme}',
    themes=dict(velvet='Sammet', winter='Vinter', sweets='Godisbutik', travel='Resa', halloween='Halloweennatt'),
    charms_h='Samla små berlocker',
    charms_p='Inslagna paket lämnar ibland en berlock. Hitta alla 12 i ett album så blir temat ditt. Gyllene paket gömmer de sällsynta.',
    feat_h='För lugna, glada minuter',
    feats=[('Gratis', 'Ladda ner och spela gratis. Stjärnpaket och reklamfritt är valfritt.'),
           ('Ingen klocka', 'Ta den tid du behöver. Spelet slutar först när ingen bit får plats.'),
           ('Spelas offline', 'Dina framsteg stannar i telefonen. Inget konto behövs.'),
           ('20 språk', 'Från English och svenska till 日本語 och العربية.')],
    faq_h='Frågor',
    faq=[('Vad är Ribbon Rush?', 'Ribbon Rush är ett gratis, mysigt blockpussel för iPhone och Android från den oberoende studion Frame Labs. Du lägger bandbitar på en 8×8-bräda för att slå in paket, tjäna stjärnor, samla berlocker och låsa upp temavärldar.'),
         ('Hur spelar man?', 'Dra bandbitar till brädan. Fyll varje ruta i den streckade ringen runt ett paket för att slå in det. Fulla rader och kolumner försvinner. Spelet slutar när ingen av dina tre bitar får plats.'),
         ('Är det gratis?', 'Ja. Spelet är gratis med reklam. Du kan köpa stjärnor eller ta bort reklamen mellan spelen, men du behöver inte.'),
         ('När kommer det?', 'Ribbon Rush kommer snart till App Store och Google Play.'),
         ('Vad är berlocker och teman?', 'Berlocker är små samlarobjekt från inslagna paket. Varje album har 12. Ett fullt album låser upp sitt tema, en ny värld för din bräda.'),
         ('Behöver jag internet?', 'Nej, du kan spela offline. Reklam och köp kräver uppkoppling.')],
    final_h='Ditt nästa paket väntar',
    final_p='Ribbon Rush kommer snart till iPhone och Android.',
    made='Gjort med omsorg', privacy='Integritet', support='Support',
)

T['ru'] = dict(
    title='Ribbon Rush – уютная блок-головоломка для iPhone и Android',
    desc='Ribbon Rush — бесплатная уютная блок-головоломка. Кладите атласные ленты на поле 8×8, заполняйте кольцо вокруг подарка и смотрите, как он упаковывается с бантом. Собирайте подвески и открывайте 16 тематических миров.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, игра упаковка подарков, блок головоломка, расслабляющая головоломка, новогодняя игра, головоломка iPhone, головоломка Android',
    skip='К содержанию', nav_label='Меню', nav=['Как играть', 'Демо', 'Темы', 'Вопросы'], lang='Язык',
    kicker='Уютная блок-головоломка',
    h1='Упакуйте каждый подарок <em>с бантом</em>',
    sub='Кладите атласные ленты на поле. Когда кольцо вокруг подарка заполнено, лента завязывается, бант раскрывается, крышка улетает и сыплются звёзды.',
    cta='Играть в демо', soon='Скоро', tap='Нажмите, чтобы упаковать',
    how_h='Как играть', how_p='Три хода — и вы знаете всю игру.',
    steps=[('Положите ленту', 'Выберите одну из трёх лент и положите её туда, где она помещается на поле 8×8.'),
           ('Заполните кольцо', 'Вокруг каждого подарка есть пунктирное кольцо. Закройте лентой каждую его клетку.'),
           ('Смотрите на упаковку', 'Лента завязывается, бант раскрывается, подарок открывается конфетти и звёздами. Полные ряды и столбцы тоже исчезают.')],
    demo_kicker='Прямо здесь', demo_h='Попробуйте в браузере',
    demo_p='Маленькая версия игры. До первого подарка — одна лента. Перетащите фигуру на поле.',
    demo=dict(score='Очки', hintTut='До первого подарка одна лента. Положите <b>розовый квадрат</b> на светящуюся клетку.',
              hint='Кладите ленты на <b>пунктирное кольцо</b> вокруг подарка. Полное кольцо упаковывает его.',
              wrapped='Упаковано', chain='Цепочка', gold='Золотой подарок ×2', over='Нет места', wrappedN='Упаковано подарков: {n}', again='Ещё раз'),
    themes_h='Шестнадцать миров',
    themes_p='Каждая тема — целая сцена со своим полем, лентами, бумагой и эффектом. Северное сияние, кондитерская, кругосветное путешествие, жуткая ночь Хэллоуина и многое другое.',
    shot_alt='Поле Ribbon Rush в теме «{theme}»',
    themes=dict(velvet='Бархат', winter='Зима', sweets='Кондитерская', travel='Путешествие', halloween='Ночь Хэллоуина'),
    charms_h='Собирайте подвески',
    charms_p='Упакованные подарки иногда оставляют подвеску. Найдите все 12 в альбоме — и его тема ваша. Редкие прячутся в золотых подарках.',
    feat_h='Для спокойных, счастливых минут',
    feats=[('Бесплатно', 'Скачайте и играйте бесплатно. Наборы звёзд и отключение рекламы — по желанию.'),
           ('Без таймера', 'Не спешите. Игра заканчивается, только когда ни одна фигура не помещается.'),
           ('Без интернета', 'Прогресс хранится на телефоне. Аккаунт не нужен.'),
           ('20 языков', 'От English и русского до 日本語 и العربية.')],
    faq_h='Вопросы',
    faq=[('Что такое Ribbon Rush?', 'Ribbon Rush — бесплатная уютная блок-головоломка для iPhone и Android от независимой студии Frame Labs. Вы кладёте ленты на поле 8×8, чтобы упаковывать подарки, получать звёзды, собирать подвески и открывать тематические миры.'),
         ('Как играть?', 'Перетаскивайте ленты на поле. Заполните каждую клетку пунктирного кольца вокруг подарка, чтобы упаковать его. Полные ряды и столбцы исчезают. Игра заканчивается, когда ни одна из трёх фигур не помещается.'),
         ('Это бесплатно?', 'Да. Игра бесплатна и содержит рекламу. Можно купить звёзды или убрать рекламу между играми, но это не обязательно.'),
         ('Когда выйдет?', 'Ribbon Rush скоро появится в App Store и Google Play.'),
         ('Что такое подвески и темы?', 'Подвески — маленькие коллекционные предметы из упакованных подарков. В каждом альбоме их 12. Полный альбом открывает свою тему — новый мир для вашего поля.'),
         ('Нужен ли интернет?', 'Нет, играть можно офлайн. Реклама и покупки требуют подключения.')],
    final_h='Ваш следующий подарок ждёт',
    final_p='Ribbon Rush скоро выйдет на iPhone и Android.',
    made='Сделано с заботой', privacy='Конфиденциальность', support='Поддержка',
)

T['id'] = dict(
    title='Ribbon Rush – Puzzle balok yang santai untuk iPhone & Android',
    desc='Ribbon Rush adalah puzzle balok gratis yang santai. Letakkan pita satin di papan 8×8, penuhi cincin di sekitar setiap kado dan lihat kado terbungkus dengan pita. Kumpulkan jimat dan buka 16 dunia bertema.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, game bungkus kado, puzzle balok, game puzzle santai, game natal, puzzle iPhone, puzzle Android',
    skip='Ke konten', nav_label='Menu utama', nav=['Cara bermain', 'Demo', 'Tema', 'Tanya jawab'], lang='Bahasa',
    kicker='Puzzle balok yang santai',
    h1='Bungkus setiap kado <em>dengan pita</em>',
    sub='Letakkan pita satin di papan. Saat cincin di sekitar kado penuh, pita terikat, simpul muncul, tutup terbang dan bintang berjatuhan.',
    cta='Main demo', soon='Segera hadir', tap='Ketuk untuk membungkus',
    how_h='Cara bermain', how_p='Tiga langkah, dan kamu sudah paham seluruh game.',
    steps=[('Letakkan pita', 'Pilih satu dari tiga potongan pita dan letakkan di mana saja yang muat di papan 8×8.'),
           ('Penuhi cincin', 'Setiap kado punya cincin putus-putus. Tutup setiap kotak cincin dengan pita.'),
           ('Lihat terbungkus', 'Pita terikat, simpul muncul, kado terbuka dengan konfeti dan bintang. Baris dan kolom penuh juga hilang.')],
    demo_kicker='Langsung di sini', demo_h='Coba di browser',
    demo_p='Versi kecil dari game. Kado pertamamu tinggal satu pita lagi. Seret potongan ke papan.',
    demo=dict(score='Skor', hintTut='Tinggal satu pita untuk kado pertama. Taruh <b>kotak merah muda</b> di kotak yang bersinar.',
              hint='Letakkan pita di <b>cincin putus-putus</b> sekitar kado. Cincin penuh membungkus kado.',
              wrapped='Terbungkus', chain='Rantai', gold='Kado emas ×2', over='Tidak ada tempat', wrappedN='{n} kado terbungkus', again='Main lagi'),
    themes_h='Enam belas dunia untuk dibuka',
    themes_p='Setiap tema adalah satu adegan utuh, dengan papan, pita, kertas kado dan efeknya sendiri. Aurora, toko permen, perjalanan keliling dunia, malam Halloween yang seram dan banyak lagi.',
    shot_alt='Papan Ribbon Rush dengan tema {theme}',
    themes=dict(velvet='Beludru', winter='Musim Dingin', sweets='Toko Permen', travel='Perjalanan', halloween='Malam Halloween'),
    charms_h='Kumpulkan jimat kecil',
    charms_p='Kado yang terbungkus kadang meninggalkan jimat. Temukan 12 jimat dalam satu album dan temanya jadi milikmu. Kado emas menyimpan yang langka.',
    feat_h='Untuk menit-menit santai dan bahagia',
    feats=[('Gratis', 'Unduh dan main gratis. Paket bintang dan hapus iklan opsional.'),
           ('Tanpa waktu', 'Santai saja. Permainan selesai hanya saat tak ada potongan yang muat.'),
           ('Bisa offline', 'Progresmu tersimpan di ponsel. Tanpa akun.'),
           ('20 bahasa', 'Dari English dan Bahasa Indonesia sampai 日本語 dan العربية.')],
    faq_h='Tanya jawab',
    faq=[('Apa itu Ribbon Rush?', 'Ribbon Rush adalah puzzle balok gratis yang santai untuk iPhone dan Android dari studio independen Frame Labs. Kamu meletakkan potongan pita di papan 8×8 untuk membungkus kado, mendapat bintang, mengumpulkan jimat dan membuka dunia bertema.'),
         ('Bagaimana cara bermain?', 'Seret potongan pita ke papan. Penuhi setiap kotak cincin putus-putus di sekitar kado untuk membungkusnya. Baris dan kolom penuh hilang. Permainan selesai saat tak satu pun dari tiga potongan muat.'),
         ('Apakah gratis?', 'Ya. Game ini gratis dengan iklan. Kamu bisa membeli bintang atau menghapus iklan antar permainan, tapi tidak wajib.'),
         ('Kapan rilis?', 'Ribbon Rush segera hadir di App Store dan Google Play.'),
         ('Apa itu jimat dan tema?', 'Jimat adalah koleksi kecil yang jatuh dari kado terbungkus. Setiap album punya 12. Menyelesaikan album membuka temanya, dunia baru untuk papanmu.'),
         ('Perlu internet?', 'Tidak, kamu bisa main offline. Iklan dan pembelian butuh koneksi.')],
    final_h='Kado berikutnya menunggumu',
    final_p='Ribbon Rush segera hadir di iPhone dan Android.',
    made='Dibuat dengan sepenuh hati', privacy='Privasi', support='Bantuan',
)

T['vi'] = dict(
    title='Ribbon Rush – Trò xếp khối thư giãn cho iPhone và Android',
    desc='Ribbon Rush là trò xếp khối miễn phí, thư giãn. Đặt ruy băng satin lên bàn 8×8, lấp đầy vòng quanh mỗi hộp quà và xem nó được gói với chiếc nơ. Sưu tầm bùa và mở khóa 16 thế giới chủ đề.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, trò chơi gói quà, xếp khối, trò chơi giải đố thư giãn, game giáng sinh, giải đố iPhone, giải đố Android',
    skip='Đến nội dung', nav_label='Menu chính', nav=['Cách chơi', 'Demo', 'Chủ đề', 'Hỏi đáp'], lang='Ngôn ngữ',
    kicker='Trò xếp khối thư giãn',
    h1='Gói mỗi món quà <em>với chiếc nơ</em>',
    sub='Đặt ruy băng satin lên bàn. Khi vòng quanh hộp quà đầy, ruy băng tự buộc, nơ bung ra, nắp bay lên và sao rơi như mưa.',
    cta='Chơi demo', soon='Sắp ra mắt', tap='Chạm để gói',
    how_h='Cách chơi', how_p='Ba bước là bạn đã hiểu cả trò chơi.',
    steps=[('Đặt ruy băng', 'Chọn một trong ba mảnh ruy băng và đặt vào chỗ vừa trên bàn 8×8.'),
           ('Lấp đầy vòng', 'Mỗi hộp quà có một vòng nét đứt. Phủ ruy băng lên từng ô của vòng.'),
           ('Xem quà được gói', 'Ruy băng buộc lại, nơ bung ra, hộp quà mở với pháo giấy và sao. Hàng và cột đầy cũng biến mất.')],
    demo_kicker='Ngay tại đây', demo_h='Chơi thử trên trình duyệt',
    demo_p='Phiên bản nhỏ của trò chơi. Món quà đầu tiên chỉ còn một ruy băng. Kéo một mảnh lên bàn.',
    demo=dict(score='Điểm', hintTut='Còn một ruy băng cho món quà đầu tiên. Thả <b>ô màu hồng</b> vào ô đang sáng.',
              hint='Đặt ruy băng lên <b>vòng nét đứt</b> quanh hộp quà. Vòng đầy sẽ gói quà.',
              wrapped='Đã gói', chain='Chuỗi', gold='Quà vàng ×2', over='Hết chỗ', wrappedN='Đã gói {n} món quà', again='Chơi lại'),
    themes_h='Mười sáu thế giới để mở khóa',
    themes_p='Mỗi chủ đề là một khung cảnh trọn vẹn, có bàn, ruy băng, giấy gói và hiệu ứng riêng. Cực quang, tiệm kẹo, chuyến du lịch vòng quanh thế giới, đêm Halloween rùng rợn và nhiều hơn nữa.',
    shot_alt='Bàn chơi Ribbon Rush với chủ đề {theme}',
    themes=dict(velvet='Nhung', winter='Mùa đông', sweets='Tiệm kẹo', travel='Du lịch', halloween='Đêm Halloween'),
    charms_h='Sưu tầm bùa nhỏ',
    charms_p='Quà đã gói đôi khi để lại một chiếc bùa. Tìm đủ 12 bùa của một album và chủ đề đó là của bạn. Quà vàng giấu những chiếc hiếm.',
    feat_h='Cho những phút chậm rãi và vui vẻ',
    feats=[('Miễn phí', 'Tải về và chơi miễn phí. Gói sao và tắt quảng cáo là tùy chọn.'),
           ('Không đếm giờ', 'Cứ thong thả. Ván chỉ kết thúc khi không còn mảnh nào vừa.'),
           ('Chơi ngoại tuyến', 'Tiến trình lưu trên điện thoại. Không cần tài khoản.'),
           ('20 ngôn ngữ', 'Từ English và Tiếng Việt đến 日本語 và العربية.')],
    faq_h='Hỏi đáp',
    faq=[('Ribbon Rush là gì?', 'Ribbon Rush là trò xếp khối miễn phí, thư giãn cho iPhone và Android của studio độc lập Frame Labs. Bạn đặt mảnh ruy băng lên bàn 8×8 để gói quà, nhận sao, sưu tầm bùa và mở khóa các thế giới chủ đề.'),
         ('Chơi thế nào?', 'Kéo mảnh ruy băng lên bàn. Lấp đầy mọi ô của vòng nét đứt quanh hộp quà để gói nó. Hàng và cột đầy sẽ biến mất. Ván kết thúc khi không mảnh nào trong ba mảnh vừa.'),
         ('Có miễn phí không?', 'Có. Trò chơi miễn phí và có quảng cáo. Bạn có thể mua sao hoặc tắt quảng cáo giữa các ván, nhưng không bắt buộc.'),
         ('Khi nào ra mắt?', 'Ribbon Rush sắp có mặt trên App Store và Google Play.'),
         ('Bùa và chủ đề là gì?', 'Bùa là vật sưu tầm nhỏ rơi ra từ quà đã gói. Mỗi album có 12 chiếc. Hoàn thành album sẽ mở khóa chủ đề của nó, một thế giới mới cho bàn chơi.'),
         ('Có cần internet không?', 'Không, bạn có thể chơi ngoại tuyến. Quảng cáo và mua hàng cần kết nối.')],
    final_h='Món quà tiếp theo đang chờ bạn',
    final_p='Ribbon Rush sắp ra mắt trên iPhone và Android.',
    made='Làm bằng cả tấm lòng', privacy='Quyền riêng tư', support='Hỗ trợ',
)

T['th'] = dict(
    title='Ribbon Rush – เกมพัซเซิลบล็อกแสนผ่อนคลายสำหรับ iPhone และ Android',
    desc='Ribbon Rush คือเกมพัซเซิลบล็อกฟรีแสนผ่อนคลาย วางริบบิ้นซาตินบนกระดาน 8×8 เติมวงรอบกล่องของขวัญให้เต็ม แล้วดูมันห่อตัวพร้อมโบว์ สะสมเครื่องรางและปลดล็อก 16 โลกธีม',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, เกมห่อของขวัญ, เกมพัซเซิลบล็อก, เกมผ่อนคลาย, เกมคริสต์มาส, เกม iPhone, เกม Android',
    skip='ไปที่เนื้อหา', nav_label='เมนูหลัก', nav=['วิธีเล่น', 'เดโม', 'ธีม', 'คำถาม'], lang='ภาษา',
    kicker='เกมพัซเซิลบล็อกแสนผ่อนคลาย',
    h1='ห่อของขวัญทุกกล่อง<em>ด้วยโบว์</em>',
    sub='วางริบบิ้นซาตินบนกระดาน เมื่อวงรอบกล่องเต็ม ริบบิ้นจะผูกเอง โบว์เด้งออก ฝากล่องปลิว และดาวโปรยลงมา',
    cta='เล่นเดโม', soon='เร็ว ๆ นี้', tap='แตะเพื่อห่อ',
    how_h='วิธีเล่น', how_p='แค่สามขั้นตอนก็เข้าใจทั้งเกม',
    steps=[('วางริบบิ้น', 'เลือกชิ้นริบบิ้นหนึ่งในสามชิ้น แล้ววางตรงไหนก็ได้ที่พอดีบนกระดาน 8×8'),
           ('เติมวงให้เต็ม', 'ของขวัญทุกกล่องมีวงเส้นประรอบ ๆ ปิดทุกช่องของวงด้วยริบบิ้น'),
           ('ดูการห่อ', 'ริบบิ้นผูก โบว์เด้ง ของขวัญเปิดพร้อมคอนเฟตตีและดาว แถวและคอลัมน์ที่เต็มก็หายไปด้วย')],
    demo_kicker='ตรงนี้เลย', demo_h='ลองเล่นในเบราว์เซอร์',
    demo_p='เกมเวอร์ชันเล็ก ของขวัญชิ้นแรกเหลืออีกแค่ริบบิ้นเดียว ลากชิ้นส่วนไปวางบนกระดาน',
    demo=dict(score='คะแนน', hintTut='เหลืออีกริบบิ้นเดียวสำหรับของขวัญชิ้นแรก วาง<b>ช่องสีชมพู</b>บนช่องที่เรืองแสง',
              hint='วางริบบิ้นบน<b>วงเส้นประ</b>รอบของขวัญ วงที่เต็มจะห่อของขวัญ',
              wrapped='ห่อแล้ว', chain='ต่อเนื่อง', gold='ของขวัญทอง ×2', over='ไม่มีที่ว่าง', wrappedN='ห่อของขวัญแล้ว {n} กล่อง', again='เล่นอีกครั้ง'),
    themes_h='สิบหกโลกให้ปลดล็อก',
    themes_p='ทุกธีมคือฉากทั้งฉาก มีกระดาน ริบบิ้น กระดาษห่อ และเอฟเฟกต์ของตัวเอง แสงเหนือ ร้านขนม การเดินทางรอบโลก คืนฮาโลวีนสุดหลอน และอีกมากมาย',
    shot_alt='กระดาน Ribbon Rush ในธีม{theme}',
    themes=dict(velvet='กำมะหยี่', winter='ฤดูหนาว', sweets='ร้านขนม', travel='ท่องเที่ยว', halloween='คืนฮาโลวีน'),
    charms_h='สะสมเครื่องรางชิ้นจิ๋ว',
    charms_p='ของขวัญที่ห่อแล้วบางครั้งจะทิ้งเครื่องรางไว้ หาให้ครบ 12 ชิ้นในอัลบั้ม แล้วธีมนั้นจะเป็นของคุณ ของขวัญทองซ่อนชิ้นหายากไว้',
    feat_h='สำหรับช่วงเวลาช้า ๆ ที่มีความสุข',
    feats=[('เล่นฟรี', 'ดาวน์โหลดและเล่นฟรี แพ็กดาวและการลบโฆษณาเป็นทางเลือก'),
           ('ไม่มีจับเวลา', 'ค่อย ๆ เล่น เกมจบเมื่อไม่มีชิ้นไหนวางได้เท่านั้น'),
           ('เล่นออฟไลน์ได้', 'ความคืบหน้าอยู่ในโทรศัพท์ ไม่ต้องมีบัญชี'),
           ('20 ภาษา', 'ตั้งแต่ English และไทย ไปจนถึง 日本語 และ العربية')],
    faq_h='คำถาม',
    faq=[('Ribbon Rush คืออะไร', 'Ribbon Rush คือเกมพัซเซิลบล็อกฟรีแสนผ่อนคลายสำหรับ iPhone และ Android จากสตูดิโออิสระ Frame Labs คุณวางชิ้นริบบิ้นบนกระดาน 8×8 เพื่อห่อของขวัญ รับดาว สะสมเครื่องราง และปลดล็อกโลกธีม'),
         ('เล่นอย่างไร', 'ลากชิ้นริบบิ้นไปวางบนกระดาน เติมทุกช่องของวงเส้นประรอบของขวัญเพื่อห่อมัน แถวและคอลัมน์ที่เต็มจะหายไป เกมจบเมื่อไม่มีชิ้นไหนในสามชิ้นวางได้'),
         ('ฟรีไหม', 'ฟรี เกมนี้เล่นฟรีและมีโฆษณา คุณซื้อดาวหรือลบโฆษณาระหว่างเกมได้ แต่ไม่จำเป็น'),
         ('จะออกเมื่อไร', 'Ribbon Rush จะมาที่ App Store และ Google Play เร็ว ๆ นี้'),
         ('เครื่องรางและธีมคืออะไร', 'เครื่องรางคือของสะสมชิ้นเล็กที่หล่นจากของขวัญที่ห่อแล้ว แต่ละอัลบั้มมี 12 ชิ้น เมื่อสะสมครบจะปลดล็อกธีม เป็นโลกใหม่สำหรับกระดานของคุณ'),
         ('ต้องใช้อินเทอร์เน็ตไหม', 'ไม่ต้อง เล่นออฟไลน์ได้ โฆษณาและการซื้อต้องใช้การเชื่อมต่อ')],
    final_h='ของขวัญชิ้นต่อไปรอคุณอยู่',
    final_p='Ribbon Rush จะมาบน iPhone และ Android เร็ว ๆ นี้',
    made='ตั้งใจทำ', privacy='ความเป็นส่วนตัว', support='ช่วยเหลือ',
)

T['hi'] = dict(
    title='Ribbon Rush – iPhone और Android के लिए सुकून भरा ब्लॉक पज़ल',
    desc='Ribbon Rush एक मुफ़्त, सुकून भरा ब्लॉक पज़ल है। 8×8 बोर्ड पर साटन रिबन रखें, हर तोहफ़े के चारों ओर का घेरा भरें और उसे रिबन के फूल के साथ पैक होते देखें। चार्म इकट्ठा करें और 16 थीम वाली दुनिया खोलें।',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, गिफ्ट रैप गेम, ब्लॉक पज़ल, आरामदायक पज़ल गेम, क्रिसमस गेम, iPhone पज़ल, Android पज़ल',
    skip='सामग्री पर जाएँ', nav_label='मुख्य मेनू', nav=['कैसे खेलें', 'डेमो', 'थीम', 'सवाल'], lang='भाषा',
    kicker='सुकून भरा ब्लॉक पज़ल',
    h1='हर तोहफ़े को <em>रिबन से</em> पैक करें',
    sub='बोर्ड पर साटन रिबन रखें। तोहफ़े के चारों ओर का घेरा भरते ही रिबन बँध जाता है, फूल खिलता है, ढक्कन उड़ता है और तारे बरसते हैं।',
    cta='डेमो खेलें', soon='जल्द आ रहा है', tap='पैक करने के लिए टैप करें',
    how_h='कैसे खेलें', how_p='तीन चालें, और आप पूरा खेल समझ गए।',
    steps=[('रिबन रखें', 'तीन रिबन टुकड़ों में से एक चुनें और 8×8 बोर्ड पर जहाँ फिट हो, रख दें।'),
           ('घेरा भरें', 'हर तोहफ़े के चारों ओर एक डैश वाला घेरा है। घेरे के हर खाने को रिबन से ढकें।'),
           ('पैक होते देखें', 'रिबन बँधता है, फूल खिलता है और तोहफ़ा कंफ़ेटी और तारों के साथ खुलता है। भरी पंक्तियाँ और कॉलम भी हटते हैं।')],
    demo_kicker='यहीं पर', demo_h='ब्राउज़र में आज़माएँ',
    demo_p='खेल का छोटा रूप। आपका पहला तोहफ़ा बस एक रिबन दूर है। एक टुकड़ा बोर्ड पर खींचें।',
    demo=dict(score='स्कोर', hintTut='पहले तोहफ़े के लिए एक रिबन बाकी है। <b>गुलाबी खाना</b> चमकती जगह पर रखें।',
              hint='तोहफ़े के चारों ओर <b>डैश वाले घेरे</b> पर रिबन रखें। पूरा घेरा तोहफ़ा पैक कर देता है।',
              wrapped='पैक हो गया', chain='चेन', gold='सुनहरा तोहफ़ा ×2', over='जगह नहीं बची', wrappedN='{n} तोहफ़े पैक हुए', again='फिर खेलें'),
    themes_h='खोलने के लिए सोलह दुनिया',
    themes_p='हर थीम एक पूरा दृश्य है, जिसका अपना बोर्ड, रिबन, रैपिंग पेपर और असर है। ध्रुवीय रोशनी, मिठाई की दुकान, दुनिया की सैर, डरावनी हैलोवीन रात और बहुत कुछ।',
    shot_alt='{theme} थीम में Ribbon Rush का बोर्ड',
    themes=dict(velvet='मखमल', winter='सर्दी', sweets='मिठाई की दुकान', travel='यात्रा', halloween='हैलोवीन की रात'),
    charms_h='छोटे चार्म इकट्ठा करें',
    charms_p='पैक हुए तोहफ़े कभी-कभी एक चार्म छोड़ जाते हैं। एल्बम के सभी 12 चार्म ढूँढें और उसकी थीम आपकी। दुर्लभ चार्म सुनहरे तोहफ़ों में छिपे हैं।',
    feat_h='धीमे, खुशनुमा पलों के लिए',
    feats=[('मुफ़्त', 'डाउनलोड करें और मुफ़्त खेलें। तारों के पैक और विज्ञापन हटाना वैकल्पिक है।'),
           ('कोई टाइमर नहीं', 'आराम से खेलें। खेल तभी खत्म होता है जब कोई टुकड़ा फिट न हो।'),
           ('ऑफ़लाइन खेलें', 'आपकी प्रगति फ़ोन में रहती है। खाते की ज़रूरत नहीं।'),
           ('20 भाषाएँ', 'English और हिन्दी से लेकर 日本語 और العربية तक।')],
    faq_h='सवाल',
    faq=[('Ribbon Rush क्या है?', 'Ribbon Rush स्वतंत्र स्टूडियो Frame Labs का iPhone और Android के लिए मुफ़्त, सुकून भरा ब्लॉक पज़ल गेम है। आप 8×8 बोर्ड पर रिबन के टुकड़े रखकर तोहफ़े पैक करते हैं, तारे कमाते हैं, चार्म इकट्ठा करते हैं और थीम वाली दुनिया खोलते हैं।'),
         ('कैसे खेलते हैं?', 'रिबन के टुकड़े बोर्ड पर खींचें। तोहफ़ा पैक करने के लिए उसके डैश वाले घेरे का हर खाना भरें। भरी पंक्तियाँ और कॉलम हट जाते हैं। जब तीनों में से कोई टुकड़ा फिट न हो, खेल खत्म।'),
         ('क्या यह मुफ़्त है?', 'हाँ। खेल विज्ञापनों के साथ मुफ़्त है। आप तारे खरीद सकते हैं या खेलों के बीच के विज्ञापन हटा सकते हैं, पर ज़रूरी नहीं।'),
         ('यह कब आएगा?', 'Ribbon Rush जल्द ही App Store और Google Play पर आ रहा है।'),
         ('चार्म और थीम क्या हैं?', 'चार्म छोटे संग्रहणीय हैं जो पैक हुए तोहफ़ों से गिरते हैं। हर एल्बम में 12 हैं। एल्बम पूरा करने पर उसकी थीम खुलती है, आपके बोर्ड के लिए नई दुनिया।'),
         ('क्या इंटरनेट चाहिए?', 'नहीं, आप ऑफ़लाइन खेल सकते हैं। विज्ञापन और खरीदारी के लिए कनेक्शन चाहिए।')],
    final_h='आपका अगला तोहफ़ा इंतज़ार में है',
    final_p='Ribbon Rush जल्द ही iPhone और Android पर।',
    made='प्यार से बनाया गया', privacy='गोपनीयता', support='सहायता',
)

T['ar'] = dict(
    title='Ribbon Rush – لغز مكعبات مريح لأجهزة iPhone وAndroid',
    desc='Ribbon Rush لعبة ألغاز مكعبات مجانية ومريحة. ضع أشرطة الساتان على لوحة 8×8، واملأ الحلقة حول كل هدية وشاهدها تُغلَّف بفيونكة. اجمع التمائم وافتح 16 عالمًا بسمات مختلفة.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, لعبة تغليف الهدايا, لغز مكعبات, لعبة ألغاز مريحة, لعبة الكريسماس, ألغاز iPhone, ألغاز Android',
    skip='انتقل إلى المحتوى', nav_label='القائمة الرئيسية', nav=['طريقة اللعب', 'تجربة', 'السمات', 'أسئلة'], lang='اللغة',
    kicker='لغز مكعبات مريح',
    h1='غلّف كل هدية <em>بفيونكة</em>',
    sub='ضع أشرطة الساتان على اللوحة. عندما تمتلئ الحلقة حول الهدية يُعقد الشريط وتظهر الفيونكة ويطير الغطاء وتتساقط النجوم.',
    cta='جرّب اللعبة', soon='قريبًا', tap='المس للتغليف',
    how_h='طريقة اللعب', how_p='ثلاث حركات وتعرف اللعبة كلها.',
    steps=[('ضع شريطًا', 'اختر قطعة من ثلاث قطع شريط وضعها في أي مكان تتسع له على لوحة 8×8.'),
           ('املأ الحلقة', 'حول كل هدية حلقة متقطعة. غطِّ كل مربع في الحلقة بالشريط.'),
           ('شاهد التغليف', 'يُعقد الشريط وتظهر الفيونكة وتنفتح الهدية بالقصاصات والنجوم. الصفوف والأعمدة الممتلئة تختفي أيضًا.')],
    demo_kicker='هنا مباشرة', demo_h='جرّبها في المتصفح',
    demo_p='نسخة صغيرة من اللعبة. هديتك الأولى على بُعد شريط واحد. اسحب قطعة إلى اللوحة.',
    demo=dict(score='النقاط', hintTut='بقي شريط واحد للهدية الأولى. ضع <b>المربع الوردي</b> في المكان المضيء.',
              hint='ضع الأشرطة على <b>الحلقة المتقطعة</b> حول الهدية. الحلقة الممتلئة تغلّفها.',
              wrapped='تم التغليف', chain='سلسلة', gold='هدية ذهبية ×2', over='لا مكان', wrappedN='تم تغليف {n} هدايا', again='العب مجددًا'),
    themes_h='ستة عشر عالمًا لفتحها',
    themes_p='كل سمة مشهد كامل بلوحتها وأشرطتها وورق تغليفها وانفجارها الخاص. الشفق القطبي ومتجر الحلوى ورحلة حول العالم وليلة هالوين مخيفة والمزيد.',
    shot_alt='لوحة Ribbon Rush بسمة {theme}',
    themes=dict(velvet='المخمل', winter='الشتاء', sweets='متجر الحلوى', travel='السفر', halloween='ليلة الهالوين'),
    charms_h='اجمع تمائم صغيرة',
    charms_p='تترك الهدايا المغلّفة أحيانًا تميمة. اعثر على تمائم الألبوم الـ12 وتصبح سمته لك. الهدايا الذهبية تخفي النادرة.',
    feat_h='لدقائق هادئة وسعيدة',
    feats=[('مجانية', 'حمّلها والعب مجانًا. حزم النجوم وإزالة الإعلانات اختيارية.'),
           ('بلا مؤقت', 'خذ وقتك. تنتهي الجولة فقط عندما لا تتسع أي قطعة.'),
           ('تعمل دون اتصال', 'يبقى تقدمك على هاتفك. لا حاجة لحساب.'),
           ('20 لغة', 'من English والعربية إلى 日本語 وTürkçe.')],
    faq_h='أسئلة',
    faq=[('ما هي Ribbon Rush؟', 'Ribbon Rush لعبة ألغاز مكعبات مجانية ومريحة لأجهزة iPhone وAndroid من الاستوديو المستقل Frame Labs. تضع قطع الشريط على لوحة 8×8 لتغليف الهدايا وكسب النجوم وجمع التمائم وفتح عوالم السمات.'),
         ('كيف ألعب؟', 'اسحب قطع الشريط إلى اللوحة. املأ كل مربع في الحلقة المتقطعة حول الهدية لتغليفها. تختفي الصفوف والأعمدة الممتلئة. تنتهي الجولة عندما لا تتسع أي من قطعك الثلاث.'),
         ('هل هي مجانية؟', 'نعم. اللعبة مجانية مع إعلانات. يمكنك شراء النجوم أو إزالة الإعلانات بين الجولات، لكن ذلك ليس ضروريًا.'),
         ('متى تصدر؟', 'تصل Ribbon Rush قريبًا إلى App Store وGoogle Play.'),
         ('ما التمائم والسمات؟', 'التمائم مقتنيات صغيرة تسقط من الهدايا المغلّفة. في كل ألبوم 12 تميمة. إكمال الألبوم يفتح سمته، عالمًا جديدًا للوحتك.'),
         ('هل أحتاج إلى الإنترنت؟', 'لا، يمكنك اللعب دون اتصال. الإعلانات والمشتريات تحتاج إلى اتصال.')],
    final_h='هديتك التالية بانتظارك',
    final_p='Ribbon Rush قريبًا على iPhone وAndroid.',
    made='صُنعت بعناية', privacy='الخصوصية', support='الدعم',
)

T['ja'] = dict(
    title='Ribbon Rush – iPhone・Android向けの癒やしのブロックパズル',
    desc='Ribbon Rushは無料の癒やし系ブロックパズル。8×8の盤にサテンのリボンを置き、ギフトのまわりのリングを埋めると、リボンが結ばれてラッピング完成。チャームを集めて16のテーマの世界を解放しよう。',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, ギフトラッピング ゲーム, ブロックパズル, 癒し パズルゲーム, クリスマス ゲーム, iPhone パズル, Android パズル',
    skip='本文へ', nav_label='メイン', nav=['遊び方', 'デモ', 'テーマ', 'よくある質問'], lang='言語',
    kicker='癒やしのブロックパズル',
    h1='すべてのギフトを<em>リボンで</em>',
    sub='盤にサテンのリボンを置こう。ギフトのまわりのリングが埋まると、リボンが結ばれ、ちょうちょ結びが咲き、ふたが飛んで、星が降ってきます。',
    cta='デモで遊ぶ', soon='近日公開', tap='タップでラッピング',
    how_h='遊び方', how_p='3ステップで、もう全部わかります。',
    steps=[('リボンを置く', '3つのリボンピースから1つ選んで、8×8の盤の空いている場所に置きます。'),
           ('リングを埋める', 'ギフトのまわりには点線のリングがあります。リングのマスをすべてリボンで埋めましょう。'),
           ('ラッピングを楽しむ', 'リボンが結ばれ、ちょうちょ結びが咲き、紙吹雪と星とともにギフトが開きます。横や縦の列がそろっても消えます。')],
    demo_kicker='ここで今すぐ', demo_h='ブラウザで遊んでみよう',
    demo_p='ゲームの小さな体験版です。最初のギフトまであとリボン1つ。ピースを盤にドラッグしてください。',
    demo=dict(score='スコア', hintTut='最初のギフトまであとリボン1つ。<b>ピンクの四角</b>を光っているマスに置こう。',
              hint='ギフトのまわりの<b>点線のリング</b>にリボンを置こう。リングが埋まるとラッピング完成。',
              wrapped='ラッピング完成', chain='連鎖', gold='金のギフト ×2', over='置ける場所がありません', wrappedN='{n}個のギフトをラッピング', again='もう一度'),
    themes_h='解放できる16の世界',
    themes_p='テーマごとに盤、リボン、包装紙、演出がまるごと変わります。オーロラ、お菓子屋さん、世界一周の旅、ちょっと怖いハロウィンの夜など。',
    shot_alt='{theme}テーマのRibbon Rushの盤面',
    themes=dict(velvet='ベルベット', winter='冬', sweets='お菓子屋', travel='旅', halloween='ハロウィンナイト'),
    charms_h='小さなチャームを集めよう',
    charms_p='ラッピングしたギフトから、ときどきチャームが出てきます。アルバムの12個をそろえると、そのテーマが手に入ります。レアなチャームは金のギフトに。',
    feat_h='ゆったり、しあわせな時間のために',
    feats=[('無料で遊べる', '無料でダウンロードして遊べます。スターパックと広告削除は任意です。'),
           ('時間制限なし', 'ゆっくりどうぞ。置けるピースがなくなるまでゲームは続きます。'),
           ('オフラインで遊べる', '進行状況はスマホに保存。アカウント不要。'),
           ('20言語に対応', 'Englishや日本語から、العربيةやTürkçeまで。')],
    faq_h='よくある質問',
    faq=[('Ribbon Rushとは？', 'Ribbon Rushは、インディースタジオFrame LabsによるiPhone・Android向けの無料の癒やし系ブロックパズルです。8×8の盤にリボンのピースを置いてギフトをラッピングし、星を集め、チャームを集めて、テーマの世界を解放します。'),
         ('どうやって遊ぶの？', 'リボンのピースを盤にドラッグします。ギフトのまわりの点線リングのマスをすべて埋めるとラッピング完成。そろった列も消えます。3つのピースがどれも置けなくなったら終了です。'),
         ('無料ですか？', 'はい。広告つきで無料です。星の購入やゲーム間の広告の削除もできますが、必須ではありません。'),
         ('いつ配信されますか？', 'Ribbon RushはまもなくApp StoreとGoogle Playで配信予定です。'),
         ('チャームとテーマとは？', 'チャームはラッピングしたギフトから出てくる小さなコレクションです。各アルバムに12個。アルバムをそろえると、そのテーマ（盤の新しい世界）が解放されます。'),
         ('インターネットは必要？', 'いいえ、オフラインで遊べます。広告と購入には接続が必要です。')],
    final_h='次のギフトが待っています',
    final_p='Ribbon RushはまもなくiPhoneとAndroidで登場します。',
    made='心をこめて', privacy='プライバシー', support='サポート',
)

T['ko'] = dict(
    title='Ribbon Rush – iPhone·Android용 아늑한 블록 퍼즐',
    desc='Ribbon Rush은 무료로 즐기는 아늑한 블록 퍼즐입니다. 8×8 보드에 새틴 리본을 놓고 선물 주위의 링을 채우면 리본이 묶이며 포장이 완성돼요. 참을 모으고 16개의 테마 세계를 열어 보세요.',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, 선물 포장 게임, 블록 퍼즐, 힐링 퍼즐 게임, 크리스마스 게임, iPhone 퍼즐, Android 퍼즐',
    skip='본문으로', nav_label='메인', nav=['플레이 방법', '데모', '테마', '자주 묻는 질문'], lang='언어',
    kicker='아늑한 블록 퍼즐',
    h1='모든 선물을 <em>리본으로</em> 포장하세요',
    sub='보드에 새틴 리본을 놓으세요. 선물 주위의 링이 가득 차면 리본이 묶이고, 나비 리본이 피어나고, 뚜껑이 날아가며 별이 쏟아져요.',
    cta='데모 플레이', soon='곧 출시', tap='탭해서 포장하기',
    how_h='플레이 방법', how_p='세 번만 두면 게임을 다 알게 돼요.',
    steps=[('리본 놓기', '세 개의 리본 조각 중 하나를 골라 8×8 보드의 빈자리에 놓아요.'),
           ('링 채우기', '선물마다 점선 링이 있어요. 링의 모든 칸을 리본으로 덮으세요.'),
           ('포장 감상하기', '리본이 묶이고 나비 리본이 피어나며 선물이 색종이와 별과 함께 열려요. 가득 찬 줄도 사라져요.')],
    demo_kicker='바로 여기서', demo_h='브라우저에서 해 보기',
    demo_p='게임의 작은 체험판이에요. 첫 선물까지 리본 하나 남았어요. 조각을 보드로 끌어 놓으세요.',
    demo=dict(score='점수', hintTut='첫 선물까지 리본 하나! <b>분홍 칸</b>을 빛나는 자리에 놓으세요.',
              hint='선물 주위 <b>점선 링</b>에 리본을 놓으세요. 링이 차면 포장 완성!',
              wrapped='포장 완료', chain='연쇄', gold='황금 선물 ×2', over='자리가 없어요', wrappedN='선물 {n}개 포장', again='다시 하기'),
    themes_h='열어 볼 16개의 세계',
    themes_p='테마마다 보드, 리본, 포장지, 효과가 통째로 바뀌어요. 오로라, 과자 가게, 세계 일주, 으스스한 할로윈 밤 등 다양해요.',
    shot_alt='{theme} 테마의 Ribbon Rush 보드',
    themes=dict(velvet='벨벳', winter='겨울', sweets='과자 가게', travel='여행', halloween='할로윈 밤'),
    charms_h='작은 참 모으기',
    charms_p='포장한 선물에서 가끔 참이 나와요. 앨범의 12개를 모두 찾으면 그 테마가 내 것이 돼요. 희귀한 참은 황금 선물에 숨어 있어요.',
    feat_h='느긋하고 행복한 시간을 위해',
    feats=[('무료', '무료로 다운로드하고 플레이하세요. 별 패키지와 광고 제거는 선택이에요.'),
           ('타이머 없음', '천천히 하세요. 놓을 조각이 없을 때만 게임이 끝나요.'),
           ('오프라인 플레이', '진행 상황은 휴대폰에 저장돼요. 계정이 필요 없어요.'),
           ('20개 언어', 'English와 한국어부터 日本語와 العربية까지.')],
    faq_h='자주 묻는 질문',
    faq=[('Ribbon Rush은 어떤 게임인가요?', 'Ribbon Rush은 인디 스튜디오 Frame Labs가 만든 iPhone·Android용 무료 아늑한 블록 퍼즐 게임이에요. 8×8 보드에 리본 조각을 놓아 선물을 포장하고, 별을 모으고, 참을 수집하고, 테마 세계를 열어요.'),
         ('어떻게 플레이하나요?', '리본 조각을 보드로 끌어 놓으세요. 선물 주위 점선 링의 모든 칸을 채우면 포장돼요. 가득 찬 가로·세로 줄은 사라져요. 세 조각 모두 놓을 곳이 없으면 게임이 끝나요.'),
         ('무료인가요?', '네. 광고가 있는 무료 게임이에요. 별을 사거나 게임 사이 광고를 없앨 수 있지만 꼭 필요하진 않아요.'),
         ('언제 출시되나요?', 'Ribbon Rush은 곧 App Store와 Google Play에 출시돼요.'),
         ('참과 테마는 무엇인가요?', '참은 포장한 선물에서 나오는 작은 수집품이에요. 앨범마다 12개가 있어요. 앨범을 완성하면 그 테마, 즉 보드의 새로운 세계가 열려요.'),
         ('인터넷이 필요한가요?', '아니요, 오프라인으로 플레이할 수 있어요. 광고와 구매에는 연결이 필요해요.')],
    final_h='다음 선물이 기다리고 있어요',
    final_p='Ribbon Rush이 곧 iPhone과 Android에 찾아와요.',
    made='정성껏 만들었어요', privacy='개인정보', support='지원',
)

T['zh'] = dict(
    title='Ribbon Rush – 适用于 iPhone 和 Android 的治愈系方块拼图',
    desc='Ribbon Rush 是一款免费的治愈系方块拼图游戏。在 8×8 棋盘上摆放缎带，填满礼物周围的一圈，看它系上蝴蝶结完成包装。收集挂饰，解锁 16 个主题世界。',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, 包装礼物游戏, 方块拼图, 治愈系益智游戏, 圣诞游戏, iPhone 益智, Android 益智',
    skip='跳到正文', nav_label='主菜单', nav=['玩法', '试玩', '主题', '常见问题'], lang='语言',
    kicker='治愈系方块拼图',
    h1='为每份礼物<em>系上蝴蝶结</em>',
    sub='在棋盘上摆放缎带。礼物周围的一圈填满时，缎带自动系好，蝴蝶结绽开，盖子飞起，星星纷纷落下。',
    cta='试玩', soon='即将推出', tap='点击包装',
    how_h='玩法', how_p='三步就能学会整个游戏。',
    steps=[('放下缎带', '从三块缎带中选一块，放到 8×8 棋盘上任何放得下的地方。'),
           ('填满一圈', '每份礼物周围都有一圈虚线格子。用缎带盖满这一圈的每一格。'),
           ('看它包好', '缎带系紧，蝴蝶结绽开，礼物在彩纸和星星中打开。填满的行和列也会消除。')],
    demo_kicker='就在这里', demo_h='在浏览器里试玩',
    demo_p='这是游戏的迷你版。第一份礼物只差一条缎带。把一块缎带拖到棋盘上吧。',
    demo=dict(score='得分', hintTut='第一份礼物只差一条缎带。把<b>粉色方块</b>放到发光的格子上。',
              hint='把缎带放在礼物周围的<b>虚线圈</b>上。一圈填满就会包好礼物。',
              wrapped='包装完成', chain='连锁', gold='金色礼物 ×2', over='没有空位了', wrappedN='包装了 {n} 份礼物', again='再玩一次'),
    themes_h='十六个世界等你解锁',
    themes_p='每个主题都是完整的场景，有专属的棋盘、缎带、包装纸和特效。极光、糖果店、环游世界、有点吓人的万圣夜，还有更多。',
    shot_alt='{theme}主题的 Ribbon Rush 棋盘',
    themes=dict(velvet='丝绒', winter='冬日', sweets='糖果店', travel='旅行', halloween='万圣夜'),
    charms_h='收集小挂饰',
    charms_p='包好的礼物有时会留下一个挂饰。集齐一本图册的 12 个挂饰，就能获得它的主题。稀有挂饰藏在金色礼物里。',
    feat_h='献给慢慢的、快乐的时光',
    feats=[('免费畅玩', '免费下载，免费游玩。星星礼包和去广告均为可选。'),
           ('没有计时', '慢慢来。只有当没有方块放得下时，游戏才结束。'),
           ('离线可玩', '进度保存在手机上，无需账号。'),
           ('20 种语言', '从 English、简体中文到日本語和 العربية。')],
    faq_h='常见问题',
    faq=[('Ribbon Rush 是什么？', 'Ribbon Rush 是独立工作室 Frame Labs 为 iPhone 和 Android 打造的免费治愈系方块拼图游戏。你在 8×8 棋盘上摆放缎带来包装礼物、赚取星星、收集挂饰并解锁主题世界。'),
         ('怎么玩？', '把缎带块拖到棋盘上。填满礼物周围虚线圈的每一格就能包好它。填满的行和列会消除。当三块缎带都放不下时，游戏结束。'),
         ('免费吗？', '是的。游戏免费并含广告。你可以购买星星或去除局间广告，但不是必须的。'),
         ('什么时候上线？', 'Ribbon Rush 即将登陆 App Store 和 Google Play。'),
         ('挂饰和主题是什么？', '挂饰是从包好的礼物中掉落的小收藏品。每本图册有 12 个。集齐一本即可解锁它的主题，为棋盘换上新世界。'),
         ('需要联网吗？', '不需要，可以离线游玩。广告和购买需要联网。')],
    final_h='下一份礼物在等你',
    final_p='Ribbon Rush 即将登陆 iPhone 和 Android。',
    made='用心制作', privacy='隐私', support='支持',
)

T['zh_Hant'] = dict(
    title='Ribbon Rush – 適用於 iPhone 和 Android 的療癒系方塊拼圖',
    desc='Ribbon Rush 是一款免費的療癒系方塊拼圖遊戲。在 8×8 棋盤上擺放緞帶，填滿禮物周圍的一圈，看它繫上蝴蝶結完成包裝。收集吊飾，解鎖 16 個主題世界。',
    keywords='ribbon rush, ribbon rush game, gift block puzzle, gift wrap game, 包裝禮物遊戲, 方塊拼圖, 療癒系益智遊戲, 聖誕遊戲, iPhone 益智, Android 益智',
    skip='跳到內文', nav_label='主選單', nav=['玩法', '試玩', '主題', '常見問題'], lang='語言',
    kicker='療癒系方塊拼圖',
    h1='為每份禮物<em>繫上蝴蝶結</em>',
    sub='在棋盤上擺放緞帶。禮物周圍的一圈填滿時，緞帶自動繫好，蝴蝶結綻開，蓋子飛起，星星紛紛落下。',
    cta='試玩', soon='即將推出', tap='點一下包裝',
    how_h='玩法', how_p='三步就能學會整個遊戲。',
    steps=[('放下緞帶', '從三塊緞帶中選一塊，放到 8×8 棋盤上任何放得下的地方。'),
           ('填滿一圈', '每份禮物周圍都有一圈虛線格子。用緞帶蓋滿這一圈的每一格。'),
           ('看它包好', '緞帶繫緊，蝴蝶結綻開，禮物在彩紙和星星中打開。填滿的列和行也會消除。')],
    demo_kicker='就在這裡', demo_h='在瀏覽器裡試玩',
    demo_p='這是遊戲的迷你版。第一份禮物只差一條緞帶。把一塊緞帶拖到棋盤上吧。',
    demo=dict(score='分數', hintTut='第一份禮物只差一條緞帶。把<b>粉紅方塊</b>放到發光的格子上。',
              hint='把緞帶放在禮物周圍的<b>虛線圈</b>上。一圈填滿就會包好禮物。',
              wrapped='包裝完成', chain='連鎖', gold='金色禮物 ×2', over='沒有空位了', wrappedN='包裝了 {n} 份禮物', again='再玩一次'),
    themes_h='十六個世界等你解鎖',
    themes_p='每個主題都是完整的場景，有專屬的棋盤、緞帶、包裝紙和特效。極光、糖果店、環遊世界、有點嚇人的萬聖夜，還有更多。',
    shot_alt='{theme}主題的 Ribbon Rush 棋盤',
    themes=dict(velvet='絲絨', winter='冬日', sweets='糖果店', travel='旅行', halloween='萬聖夜'),
    charms_h='收集小吊飾',
    charms_p='包好的禮物有時會留下一個吊飾。集齊一本圖冊的 12 個吊飾，就能獲得它的主題。稀有吊飾藏在金色禮物裡。',
    feat_h='獻給慢慢的、快樂的時光',
    feats=[('免費暢玩', '免費下載，免費遊玩。星星禮包和移除廣告皆為選購。'),
           ('沒有計時', '慢慢來。只有當沒有方塊放得下時，遊戲才結束。'),
           ('離線可玩', '進度儲存在手機上，無需帳號。'),
           ('20 種語言', '從 English、繁體中文到日本語和 العربية。')],
    faq_h='常見問題',
    faq=[('Ribbon Rush 是什麼？', 'Ribbon Rush 是獨立工作室 Frame Labs 為 iPhone 和 Android 打造的免費療癒系方塊拼圖遊戲。你在 8×8 棋盤上擺放緞帶來包裝禮物、賺取星星、收集吊飾並解鎖主題世界。'),
         ('怎麼玩？', '把緞帶塊拖到棋盤上。填滿禮物周圍虛線圈的每一格就能包好它。填滿的列和行會消除。當三塊緞帶都放不下時，遊戲結束。'),
         ('免費嗎？', '是的。遊戲免費並含廣告。你可以購買星星或移除局間廣告，但不是必須的。'),
         ('什麼時候上架？', 'Ribbon Rush 即將登上 App Store 和 Google Play。'),
         ('吊飾和主題是什麼？', '吊飾是從包好的禮物中掉落的小收藏品。每本圖冊有 12 個。集齊一本即可解鎖它的主題，為棋盤換上新世界。'),
         ('需要連網嗎？', '不需要，可以離線遊玩。廣告和購買需要連網。')],
    final_h='下一份禮物在等你',
    final_p='Ribbon Rush 即將登上 iPhone 和 Android。',
    made='用心製作', privacy='隱私', support='支援',
)
